### ISSUE TITLE
LINUX - fullscreen toggle not working 

### ISSUE THREAD

**Issue by zuotian3619** [TASEmulators/desmume#340]
running on xfce. cannot exit fullscreen even after uninstalling/reinstalling. neither esc nor alt+enter work.

**Comment by zeromus** [comment]
hey @sietschie -- you have a recent commit here regarding fullscreen in linux. This subject might interest you?
@zuotian3619 you might find that desmume in retroarch is a better expereience in linux than desmume is

**Comment by Salz** [comment]
The patch in https://github.com/TASEmulators/desmume/pull/492 brings back the "view"-pop-up menu (from gtk2), which enables you to untoggle fullscreen. If I understand you correctly this should fix your issue?

**Comment by linkmauve** [comment]
Fixed in #492.
