### ISSUE TITLE
LINUX - Can't get menu bar back after disappearing

### ISSUE THREAD

**Issue by D0J0P** [TASEmulators/desmume#407]
I downloaded the latest version as a Flatpak. I accidentally clicked to hide the menu, and there's no way in the GUI to bring it back. I tried right-clicking everywhere, and the context menu doesn't show an option to bring the menu bar back. I tried uninstalling and reinstalling, but it reinstalled with the same settings.

**Comment by linkmauve** [comment]
How do other software solve this issue?  Or did they drop the ability to hide the menu?  I’m not well-versed in UI design, sorry. :x

**Comment by D0J0P** [comment]
I don't even think DeSmuMe on Windows 10 has a "hide menu" option, only a "hide toolbar" option, which is very easy to undo as the menu is still there. I can't do that on Linux as the entire menu is gone, and there's no way in the GUI to get it back.

**Comment by zeromus** [comment]
brainstorming: hit hotkey to bring it back and write hotkey in manual, or write config key to manually edit in manual. Or don't save that setting and make users hide it every time.

**Comment by tvvoty** [comment]
So, is there a way to get it back at all? I tried reinstalling it but that didn't work.

**Comment by tvvoty** [comment]
> brainstorming: hit hotkey to bring it back and write hotkey in manual, or write config key to manually edit in manual. Or don't save that setting and make users hide it every time.

A hotkey makes the most sense. Atom uses Alt for showing\hiding the menu for example.

**Comment by Salz** [comment]
The patch in https://github.com/TASEmulators/desmume/pull/492 brings back the pop-up menu from gtk2, which should fix this issue.

**Comment by linkmauve** [comment]
Fixed in #492.
