### ISSUE TITLE
Inaccessible downloads of latest builds

### ISSUE THREAD

**Issue by RokkumanX** [TASEmulators/desmume#460]
DeSmuME's main page states that stable releases have problems and should be avoided and let's be honest that we can all agree to that!

There is a link to the ci appveyor page which is totally fine but due to how ci appveyor handles things, the builds contained there auto deletes after 1 month and the last available download went off the air a couple of days ago.

Ci appveyor is great in that regard that as long as a project have continuous activity and gets updated frequently, builds will not run out.

But as soon as activity starts fading out, build after build gets deleted leaving you with a message telling you `The build job does not contain any artifacts. `

Unless you are like me who frequently checks projects and downloads chances are you will not have access to latest builds when the time comes.

I've seen numerous projects here on GitHub that have artifacts downloadable straight from the repository, to name a few examples here: pcsx2, ppsspp, m64p, duckstation, ares etc.

You need to have a GitHub account to be able to download but it's a small price to pay to have access to the latest builds.

Sure there are alternatives, EmuCR among many others.
Personally I don't really recommend 3rd party alternatives since you never know if those builds have been tampered with or not.

What could be a long term solution for DeSmuME when it comes to latest builds accessibility?

Thank you for all your hard work!

**Comment by RokkumanX** [comment]
I forgot to mention that it seems that at one point in time DeSmuME builds were provided by the Orphis buildbot which also hosts builds of pcsx2 and ppsspp.

Maybe you could reconnect and have that as a solution? Last build seems to be from 2016, was there a perticular reason behind the sudden stop there?

**Comment by FroyoXSG** [comment]
[DeSmuME.zip](https://github.com/TASVideos/desmume/files/6949070/DeSmuME.zip)
I assume nobody minds me posting this. x86_64 commit 73af0c6e
+1 for builds on GitHub

**Comment by zeromus** [comment]
Who's gonna put builds on github and make a tag on every single commit just to placate github? Looks like @FroyoXSG has got it covered by posting them here in the thread. How about you make a new thread with ALWAYS LATEST BUILD so you can continually revise the 1st post and I'll link to it from desmume.org

**Comment by FroyoXSG** [comment]
I don't think anyone was thinking of doing this manually.
Anyway, I can look into adapting and expanding some code from my own [updater program](https://github.com/FroyoXSG/superelixier-updater) to create some kind of bot that grabs artifacts from AppVeyor and mirrors them into a repo along with the code. Only if it's cool with the DeSmuME team, of course.
I should have time at to do this by the end August.

**Comment by zeromus** [comment]
You can't put builds on github without spamming tags in your repository. Prepare the tool to put them on sourceforge and I will be more impressed.

**Comment by RokkumanX** [comment]
When I created this issue I wasn't sure what to expect, but I kinda knew I'd be working myself uphill.

First of there is no spamming of tags, do check out my fork of [Mesen](https://github.com/RokkumanX/Mesen)
The only tags that are there are release tags which are from SourMesen when he had the project going actively.

Honestly I haven't done anything with my fork expect keeping it up to date with commits from other forks, the GitHub builder sorta came with the package.

Look closely at the commits section and you'll find a green check mark which if clicked will take you to [this](https://github.com/RokkumanX/Mesen/runs/3268755451)

Now when you are there things kinda reminds of Ci Appveyor and you ALWAYS have the ability to download the artifact/latest build.

My fork doesn't look cluttered and there sure are no spamming of tags as far as I can see.

Also @FroyoXSG was nice enough to share the last build that were available from Ci Appveyor, something he did on his own free will and he owes no one this favor.

What would starting a new thread have for purpose when the said thread have to rely on builds from Ci Appveyor which in itself relies on project activity.

Let's see here, checking the history in Ci Appveyor, the last "official" build were from you @zeromus dated back April 9th (winport: fix number 442 - 0.0.0.798) and which by already explained reasons is no longer available since 3 months back.

That's four months of "official" inactivity, but a new pull request dated 6th of July came in (NWRAM Initialization for a consistent startup setting. (Was handled by the default initialization, which might not be valid in all compiler settings) - 0.0.0.800) which made the possibility to be able to download the "latest" build available for another month.

Anyway I made this longer than it had to be, but I don't really see why it would be up to us, the end users to create a solution handed over nicely on a silver platter.

Honestly if there is no inteterst keeping the project alive then by all means end it, but we are trying to be civilized and trying to come up with ways, long term ways solving the build accessibility problem.

And I never got an answer to why the builds from the Orphis Buildbot completely stopped, unless you literly told the man to f*** off you might want to reconnect with him again and work something out.

`The server is running on a dedicated host and new projects could easily be built here. If you want your project to be built and distributed here, send me a mail at "buildbot nospam orphis.net" and we'll discuss it.`

Doesn't cost a nickel.

**Comment by zeromus** [comment]
I didn't know github was allowing users to build software on windows VMs and upload infinite builds without paying the nuisance tax of making tagged releases. I guess there was a silver lining to microsoft buying it after all. If you want to set this up on our desmume project, I'll give you access.

Orphis has been AWOL since 2016.

**Comment by RokkumanX** [comment]
I never thought I would say this but that was the most sincere and nicest comment I've seen from you.

You know, I love DeSmuME so much and I'd hate if the project were to die out (you know I love the project when I have the decency to spell the project's name correctly)

When it comes to GitHub building I'll have to investigate on how this works more thoroughly because I have no clue on how I can have my own builds of a project I forked (referring to Mesen again)

**Comment by Tekkenlord-X** [comment]
This is all AppVeyor fault deleting the items in only 1 month which is ridiculous, 6 months is ok but 1 month? they are fu**** retards, or a fuc**** retard has taken over...

**Comment by Jules-A** [comment]
It's not pretty but I guess you could always just push a dummy commit to force a AppVeyor rebuild?

**Comment by RokkumanX** [comment]
I've been busy for a few days now but I just noticed that you could download the April 9th build again from the CI Appveyor, looks good to me!

If you feel satisfied you can close the issue if you want, otherwise if you think there is more to add or do feel free to leave it open.

Thanks a lot for your help, really appreciate it!

**Comment by zeromus** [comment]
I'm leaving this open til it happens next time. Whoever accepts responsibility will get commit permissions to update the file each month.

**Comment by RokkumanX** [comment]
Sorry for reviving this but I'm getting these errors when I'm attempting to download the latest builds from ci appveyor

{"message":"Artifacts download limit (1024 MB/day) exceeded."}

They really don't want people to download anything.

**Comment by zeromus** [comment]
this thread is no longer needed since we have to abandon appveyor completely
https://github.com/TASEmulators/desmume/issues/500
