### ISSUE TITLE
[MAC] problem with lanczos output filters on some systems

### ISSUE THREAD

**Issue by Ac-Gamer** [TASEmulators/desmume#476]
App Version: v0.9.12
Operating System: Mac OS X v10.13.6 (17G14042)
Model Identifier: MacBookAir7,2
ROM Name: MARIOKARTDS
ROM Serial: NTR-AMCE-USA
-----------------------------------
Emulation Speed: 1.00x
Auto Frame Skip: NO
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Auto
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 18-bit
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Audio - Output Engine: OS X Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method
-----------------------------------
Cheats: YES (ActiveCheatCount=0)
-----------------------------------
Observed Behavior: I was just trying to test to see if the data of the rom being uploaded to the internet and and downloaded back would restore the data, I found out that it doesn’t work. Then I tried opening one of the games and I saw a strange glitch in the screen, like everything was distorted, and when I make the screen bigger it just becomes worse, it doesn’t just happen with Mario kart, but with other rom/games too I think its the emulator thats the problem as every game I load has the same glitchy screen.

Expected Behavior: Unspecified

**Comment by Ac-Gamer** [comment]
![Screen Shot 2021-10-19 at 9 32 51 AM](https://user-images.githubusercontent.com/92767727/137855112-ea7b5db8-f963-474d-8c6f-3fb3bc07e5d0.png)

here is a screenshot of what I'm talking about

**Comment by Ac-Gamer** [comment]
the option is : lanczos2 and lanczos3

**Comment by rogerman** [comment]
I am quite shocked that this is happening on a MacBook Air 7,2, which has an Intel HD 6000 iGPU. You are running macOS High Sierra, for which this OS and GPU combination supports Metal. Therefore, DeSmuME should be using the Metal blitter on your configuration. I've done quite a bit of testing with the Metal blitter, and Lanczos2 and Lanczos3 certainly work perfectly on Metal under all conditions.

However, the OpenGL blitter's testing has fallen short, and so there may be some bugs that may remain there. I've already confirmed some of graphical bugs in the OpenGL myself, and will be fixing it there when my time permits. However, the graphical bugs I've found do not match up with your screenshot.

Which brings me back to some questions: @Ac-Gamer, are you running your MacBook Air 7,2 with the OpenGL blitter? If so, how did you do this? Are you running the dev+ build and modified some developer-only settings?

**Comment by Ac-Gamer** [comment]
OpenGL blitter? im not quite sure what you mean, but I think not, and I don't think I'm running the dev+ build, I also I don't have access to "dev only settings".

**Comment by rogerman** [comment]
@Ac-Gamer, I've uploaded a new version of DeSmuME for Mac on our Downloads page for May 8, 2022. You can get it from here:
http://desmume.org/download/

Can you let us know if this is still a problem with this version?

**Comment by Ac-Gamer** [comment]
I know this is an odd question, but how do I update? This is actually my first time trying to update Desmume.

**Comment by rogerman** [comment]
See my previous post. Download the May 8, 2022 update for Mac DeSmuME from our Downloads page:
http://desmume.org/download/

**Comment by Ac-Gamer** [comment]
updated to the may 8 2022 build and tried the lanczos2 filter on the same game, this is what I see
![Screen Shot 2022-05-10 at 11 41 16 AM](https://user-images.githubusercontent.com/92767727/167538265-fcc77b56-f361-4a45-a81f-9133e0a2a11c.png)

the screen looks different from the previous version but it still happens.

**Comment by rogerman** [comment]
@Ac-Gamer, can you go to Help > Submit a Bug Report and post the troubleshooting information here again? You don't have to fill in Observed Behavior or Expected Behavior again -- I just need to see what is being reported for "Video - Output Engine".

**Comment by Ac-Gamer** [comment]
[ BEGIN DESMUME TROUBLESHOOTING INFORMATION ]

App Version:  0.9.12 x64 SSE4.2+AVX2 (LLVM-Clang v13.1.6)
Operating System: Mac OS X v10.13.6 (17G14042)
Model Identifier: MacBookAir7,2
ROM Name: MARIOKARTDS
ROM Serial: NTR-AMCE-USA

Emulation Speed: 1.00x
Auto Frame Skip: NO
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Auto
Advanced Bus-Level Timing: NO
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 24-bit
3D Renderer - Engine: None (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Video - Output Engine: macOS Metal GPUFamily1_v3 (Intel(R) Iris(TM) Graphics 6000)
Audio - Output Engine: macOS Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method

Cheats: NO

Observed Behavior: Unspecified

Expected Behavior: Unspecified

[ END DESMUME TROUBLESHOOTING INFORMATION ]

**Comment by Ac-Gamer** [comment]
the bug also seems to happen on the bicubic B-spline filter

**Comment by rogerman** [comment]
@Ac-Gamer, try quitting DeSmuME first, then go into Terminal and enter this command exactly as shown:
`defaults write org.desmume.DeSmuME.plist Debug_DisableMetal YES`

Then relaunch DeSmuME. Post your screenshot again and repost the DeSmuME troubleshooting info again, thanks.

**Comment by Ac-Gamer** [comment]
i quit desmume, entered the command, went back to desmume, set the filter to Lanczos 2, at first it was just a black screen with no gameplay, but after restarting it this is what I found
![Screen Shot 2022-05-10 at 12 04 59 PM](https://user-images.githubusercontent.com/92767727/167540571-24bf6e2a-b119-44b0-b988-f674cc46c283.png)
(the black line in the middle is just the display separation)

the bug (for lanczos 2,3 and bicubic B-spline) is gone.
However, I did notice after the command was that everytime I click the x button while a game is running instead of just stopping the rom and going to a black screen, when I click the x button it exits the rom but the game screen is just there, just freezing. 
![Screen Shot 2022-05-10 at 12 11 44 PM](https://user-images.githubusercontent.com/92767727/167541147-716ab7d6-2424-4e3a-bb21-f52f82dac3b7.png)


[ BEGIN DESMUME TROUBLESHOOTING INFORMATION ]

App Version:  0.9.12 x64 SSE4.2+AVX2 (LLVM-Clang v13.1.6)
Operating System: Mac OS X v10.13.6 (17G14042)
Model Identifier: MacBookAir7,2
ROM Name: MARIOKARTDS
ROM Serial: NTR-AMCE-USA

Emulation Speed: 1.00x
Auto Frame Skip: NO
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Auto
Advanced Bus-Level Timing: NO
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 24-bit
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Video - Output Engine: macOS OpenGL v4.1 (Intel(R) HD Graphics 6000)
Audio - Output Engine: macOS Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method

Cheats: NO

Observed Behavior: Unspecified

Expected Behavior: Unspecified

[ END DESMUME TROUBLESHOOTING INFORMATION ]

**Comment by rogerman** [comment]
Very interesting. It works in OpenGL and not in Metal. 

@Ac-Gamer, if you have the time, could you test out all the other filters in Metal? I'll need you to quit DeSmuME first, then go back into Terminal and enter the following:
`defaults write org.desmume.DeSmuME.plist Debug_DisableMetal NO`

Please test every video filter, as I don't have a MacBookAir7,2 on hand, and any information at all would be helpful. I would very much like to get this issue resolved before the 0.9.12 release.

So I know what Bicubic (B-Spline), Lanczos2, and Lanczos3 do. Now I need to know what Nearest Neighbor, Bilinear, and Bicubic (Mitchell-Netravali) do.

Also, if you could test Deposterize, as well as all of the filters listed under the Video Pixel Scaler menu, that would be great. To aid you in this, use the Video Settings panel under Video > Show Video Settings... to help speed up this process.

**Comment by Ac-Gamer** [comment]
sure thing but I would probably get this tested this weekend or after because of school and other stuff, if that's okay.

**Comment by rogerman** [comment]
It should literally take a few minutes. You just need to click through the filters in the Video Settings panel and note which filters look messed up and which ones look fine. You don't need to post individual screenshots for each filter -- I just need to know which filters fail and which ones don't.

**Comment by Ac-Gamer** [comment]
So aside from lanczos2,3 Bicubic B-spline having the bug, Bicubic (Mitchell-Netravali) also has the bug. Bilinear and nearest neighbor is fine though. Basically only nearest neighbor and bilinear don't have the bug but the other filters do. When deposterized checked, its the same thing, nearest neighbor and bilinear is fine but the other filters have the bug.

**Comment by rogerman** [comment]
Okay, so set the Output Filter to Bilinear.
With the Bilinear Output Filter, what happens when you use the Pixel Scalers?

And one more thing... could you tell me what happens when you choose View > Enable Heads-Up Display ? Toggle some of the options under View > HUD Info Visibility. Does the HUD render correctly, or is that corrupted as well?

**Comment by Ac-Gamer** [comment]
when output was set to bilinear, many of the pixel scalers I tested worked fine and changed to the pixel scaler without a problem. 

Also, The HUD in the screen renders fine, text is clear, and is not corrupted.

**Comment by rogerman** [comment]
> many of the pixel scalers I tested worked fine

"Many" is not all. Were there some pixels scalers that failed?

**Comment by Ac-Gamer** [comment]
just tested them all, worked fine

**Comment by rogerman** [comment]
@Ac-Gamer, I've attempted to fix this issue using four slightly different methods. Hopefully, at least one of them will work.

Please test the video output filters: Bicubic (B-Spline), Bicubic (Mitchell-Netravali), Lanczos2, and Lanczos3 filters. Let me know which ones work and which ones fail.

Use the latest nightly build for your testing:
https://nightly.link/TASEmulators/desmume/workflows/build/master/macos.zip

**Comment by Ac-Gamer** [comment]
so Bicubic B-spline works fine, Bicubic (Mitchell-Netravali) Has the screen bug, Lanczos2 also works fine, While Lanczos3 has the bug.

**Comment by rogerman** [comment]
@Ac-Gamer, I've refined the fixes for those four video output filters. Could you please check them again? You can download the nightly build using the same link that I posted above for your testing.

I am predicting that Bicubic (B-Spline), Bicubic (Mitchell-Netravali), and Lanczos2 will work. However, Lanczos3 is the big question mark -- I don't know whether this one will work or fail.

**Comment by Ac-Gamer** [comment]
so after testing, i noticed that all the filters that previously had the bug, [bicubic (B-spline), Bicubic (Mitchell-Netravali), lanczos2 and lanczos3] now doesn't have the output bug.
