### ISSUE TITLE
Game freezes after logo

### ISSUE THREAD

**Issue by BlueTigress07** [TASEmulators/desmume#483]
Every time I try to load Rabbids Go Home it shows the ubisoft logo and freezes on a black screen with no audio. After it sits for a bit, In the second window it says “ARM9: undefined instructions: 0xEA000075 PC=0x02004000” . This is the only game that does this

 I looked around for answers but couldn't find any fixes. Im not great with these sorts of errors so a slightly more detailed suggestion or fix would be greatly appreciated

**Comment by zeromus** [comment]
Works fine for me. Stop using a million years old version of desmume or cheating or patching, or else make sure your rom isn't corrupted.

**Comment by zeromus** [comment]
That's useful information, but then why do my notes from 3 years ago say it worked just fine for me?

**Comment by Sukotto-1999** [comment]
Welp, the game crashes for me, maybe should add a commit to emulate this load precision or implement a cheat code to get it working

**Comment by Sukotto-1999** [comment]
Okay, adjusting is complex. Just for now, you either use DS-Scene Rom Tool with my updated custom database or use action replay code for the game to work.

US:
5203CF18 E28DD02C
0203CF18 EB0F0878
D2000000 00000000
023FF100 E59D1000
E23FF104 00000030
E3510001 1A000003
E28F1010 E891001E
E5813000 E5824000
E28DD02C E12FFF1E
0218D5C4 0218D5CC
E3A05921 E3A04000
D2000000 00000000

EUR:
5203D108 E28DD02C
0203D108 EB0EFCBC
D2000000 00000000
023FF100 E59D1000
E23FF104 00000030
E3510001 1A000003
E28F1010 E891001E
E5813000 E5824000
E28DD02C E12FFF1E
0218DA4C 0218DA54
E3A05921 E3A04000
D2000000 00000000

**Comment by rofl0r** [comment]
> The game runs 100 rom reads of 0x4000 bytes and times how long will it take. The loading time must take around 80000 and 88000 ticks (152 to 168ms) or the game will hang before the title screen.

do you know the actual time it takes with desmume ?

**Comment by taxicat1** [comment]
> do you know the actual time it takes with desmume ?

It consistently takes 0x7E046 ticks on US and 0x7E050 on EU. Only *slightly* too fast.

The check exists in overlay 1, which makes it difficult to patch, and the existing AP patching methods (intended for flashcarts) consist of code that hooks onto `MIi_UncompressBackward` or `FS_LoadOverlay`, checks if overlay 1 is being loaded, and then applies a patch after the overlay is loaded but prior to cache flushing. This is one I wrote:

US: `0x0218D518 = E3A00001`
EU: `0x0218D9A0 = E3A00001`

Or as AR-style:
US
```
5218D518 EBFAFF8F
0218D518 E3A00001
D2000000 00000000
```

EU
```
5218D9A0 EBFAFEE9
0218D9A0 E3A00001
D2000000 00000000
```

**Comment by taxicat1** [comment]
Here is the function decompilation for the test: https://pastebin.com/W6NkAhnk
This could potentially be fixed without a patch by (somehow) slowing down the ROM read speeds by about 5%

**Comment by BlueTigress007** [comment]
holy shit i just checked my emails and i did not expect to see this actually get at least somewhat solved after it got closed, the ar code works perfectly for what i needed so thank you!!
