### ISSUE TITLE
What can be done to improve emulation performance on low-mid range Android devices

### ISSUE THREAD

**Issue by ryu-ketsueki** [TASEmulators/desmume#488]
It's been a while that I am playing NDS games on DraStic, a paid, closed source NDS emulator for Android, simply because it's got better performance in general, even when the game is running at a higher internal resolution than normal. I compared the performance between DraStic and DeSmuME on a Xiaomi Redmi 9, with Mediatek G80 and it got to a point that wasn't even necessary to do some true benchmarks to compare the two. The difference was extreme. While games like Super Mario 64 DS and Pokémon Black would run without performance loss at all, allowing even to increase the internal resolution a bit and still have the same experience, DeSmuME, more specifically in the RetroArch core, have severe emulation speed loss, making the game run very slow to about 50% of the intended speed and perhaps less.

But then I ask. What is DraStic doing of special that makes it a good NDS emulator for this device? I also used to run it on the old Redmi 2, which didn't allow for the increased internal resolution but did allow for some decent NDS gameplay, while DeSmuME or other emulators based on it, didn't.

Could DraStic be reverse engineered somehow? Or could a similar performance be achieved with some configuration on Android? Focusing on RetroArch, I could take this to the maintainers of the core if asked but I wanted to ask here if something had to be done on this side first to try improve the performance on Android, so paid emulators like DraStic would be no longer necessary.

**Comment by zeromus** [comment]
So you've been paying a guy for years for a great emulator, and tonight you decide to ask the guys you haven't been paying why their emulator isn't great.
