### ISSUE TITLE
[Linux, OpenAL] Microphone always returning noise

### ISSUE THREAD

**Issue by Salz** [TASEmulators/desmume#490]
Running the current HEAD from git (0b4b58f3b4ccbb300b1718b0917bc1ef5804df85), the microphone always produces noise, triggering an escape in Lunar: Dragon Song on any fight.

It seems the values returned by Mic_ReadSample() in mic_openal.cpp are not in the expected format. All other drivers return on byte with bits 7-1 shifted one to the right, and then followed by one byte with bit 0 shifted seven to the left. Since the DS mic is returned through an SPI bus, this might be the intended design, though it looks like a really weird decision.

Copying this bit shuffle logic from other mic drivers fixes the OpenAL microphone input.

See pull request https://github.com/TASEmulators/desmume/pull/489 for the fix.

**Comment by zeromus** [comment]
merged
