### ISSUE TITLE
Dependency on Anti-Grain Geometry library

### ISSUE THREAD

**Issue by berdario** [TASEmulators/desmume#494]
The webpage of the library in question disappeared in October:

https://web.archive.org/web/20210901155345/http://antigrain.com/

Now it yields

> This Account has been suspended

I see that @ghaerr forked the project and ostensibly released a new 2.6 version:

https://github.com/ghaerr/agg-2.6#roadmap

You should probably do one of:

* vendor agg, and keep it in desmume's repo
* check that the changes from ghaerr are sensible, and adopt his version
* create your own fork of agg

**Comment by zeromus** [comment]
isnt the old libagg we use in all the package repositories? why does it matter if the homepage is gone?

**Comment by ghaerr** [comment]
Hello @berdario and @zeromus,

The original webpage for AGG expired after Maxim's passing, and an unmodified build of all the AGG demos required downloading some additional images from the website. So, a couple years ago I copied the entire repository from sourceforge with history, including the last-released version 2.6, and put it up on GitHub. The only changes made have been to support an additional platform (nano-X), which did not change any AGG 2.6 files. In addition, PDFs of all the original website AGG documentation has also been uploaded separately.

Thank you!

**Comment by zeromus** [comment]
I dont understand why any of this matters. isnt the old libagg we use in all the package repositories?

**Comment by berdario** [comment]
> isnt the old libagg we use in all the package repositories? why does it matter if the homepage is gone?

I thought it was obvious but:

If you want to build this software, you need to specify where to get the dependency from. If that place goes away, the build is broken.

Likewise, Linux distributions are also the kind of entities that have policies for describing where dependencies come from. If they realize that the dependency is unmaintained, they might decide to remove it from their repositories.

They might not care right now, until a compiler update or libc update might cause agg to stop building. In that case, they won't reach out to you: if it's unmaintained upstream, they are likely to remove it.

Not addressing this issue means kicking the can down the road. 🤷

**Comment by zeromus** [comment]
This isn't mission critical software. When it breaks, we'll fix it.
