### ISSUE TITLE
RTC Time Event bug Pokemon White/Black

### ISSUE THREAD

**Issue by emiceta** [TASEmulators/desmume#498]
In Pokemon White/Black there are some events that triggers after one day or one week (You can rematch a pokemon trainer the next day or next week if you win against them). But after that time, the game doesn't appear to know how time has passed since the last time you played so that it's like no time has passed at all. **With legitimate in-game save and load and no AR code**.

What I've found is that If I change the date forward _without_ exiting desmume, the game recognizes it and it works just fine. But if I exit desmume and do the same, it's like I said at the beginning: the game seems to think no time has passed.

Also, it doesn't matter if I quick save or quick load or is in-game save & load. As long as I don't exit desmume, it works. So I'm pretty sure that this issue has nothing to do with anticheating methods from the game, but a bug from the emulator.

So my guess is that this issue is concerning about the rtc. Maybe saving a variable so the emulator, and therefore the game, recognizes the time that has passed since you saved and exit the game until you play again.

**Comment by zeromus** [comment]
http://forums.desmume.org/viewtopic.php?pid=29256

**Comment by emiceta** [comment]
Thank you. With just testing the latest release it would've been enough. Sorry to bother you -.-'
