### ISSUE TITLE
Is it possible to add Action Replay Cheats to Desmume still?

### ISSUE THREAD

**Issue by worldpe** [TASEmulators/desmume#499]
Sorry for asking here, but I have been trying to find this out for a few days. I can find videos and forum posts on this from 2010 and earlier, but nothing after and the feature seems to be gone. Is there some other way to go about this now? Reading through issues on this page, I found something related to putting .dst files in some folder, but I can't find any information on this.

**Comment by zeromus** [comment]
The feature didn't go anywhere. If you've had the experience of seeing no mechanism for adding AR cheats then it's because you're using the linux or mac version which may lack them. Use windows and try again.

**Comment by worldpe** [comment]
Oh, I am using the flatpak, I wouldn't expect a feature to missing across versions.

**Comment by zeromus** [comment]
You must be new to emulators and/or linux if you expected feature parity across platforms.
