### ISSUE TITLE
Problem with controller

### ISSUE THREAD

**Issue by XiNaru** [TASEmulators/desmume#504]
Hey Guys,

I have a very big problem.

In fact:
I also use Cemu and use a Switch Pro Controller for it, works perfectly. without problems.

Now I wanted to set this up for DESMUME as well, but... the buttons are pressed without me doing anything. I can't change any controller settings and when I start a game things happen automatically without me doing anything.

**Comment by zeromus** [comment]
are buttons pressed automatically with the switch pro controller disconnected?

**Comment by XiNaru** [comment]
no...its only if the controller is connected.
with cemu i havent this problem

**Comment by zeromus** [comment]
we have been having a problem for years where spurious inputs get produced inside desmume somehow. I have never been able to reproduce it. What OS are you on and what 3rd party pieces (joymappers, drivers, etc.) are you using to connect the switch pro controller?
Also try these things:
1. another usb port
2. reboot your computer

**Comment by XiNaru** [comment]
nothing else.
i have windows 10 home
and have only plug & play with my switch pro controller.


i try an other usb port..mom
..... okay tried, the same problem.
pc restart doesnt help

**Comment by zeromus** [comment]
You have it connected by USB? Or it's using bluetooth somehow?

**Comment by XiNaru** [comment]
with usb yes

**Comment by zeromus** [comment]
I can't even get it to work on my windows 10 PC. That suggsts you've used some 3rd party software to make it work. Get support from 3rd party software vendor.
