### ISSUE TITLE
Mark Mode in Console Makes DeSmuME Not Responding

### ISSUE THREAD

**Issue by abx-dx** [TASEmulators/desmume#507]
I've found that by coincidence (Double clicking on a text at console) and i realized it can be reproduced by 2 ways:

1) Open DeSmuME directly (while there is not a ROM loaded), get mark mode at console. If you try to load any ROM, main window will freeze and not respond.
2) While a ROM is loaded, get mark mode at console. If you activate main window, it will freeze and not respond.
Note 1: If you exit mark mode at console without activate main window there is not problem.
Note 2: Maybe this issue comes from how Command Prompt works, not related with DeSmuME.

I first encountered this issue with the nightly build at #500 @zeromus gave, then i tried it with build 0.0.0.905 and i got same result (I couldn't try last build because of "Artifacts download limit (1024 MB/day) exceeded.").

**Comment by zeromus** [comment]
that's how windows works.
