### ISSUE TITLE
ARM NEON support?

### ISSUE THREAD

**Issue by MaddTheSane** [TASEmulators/desmume#509]
Looking through the code, I noticed that there's not a whole lot of NEON optimizations.
There's two ways NEON support can be added: using [sse2neon](https://github.com/DLTcollab/sse2neon), which wraps SSE calls with their NEON counterparts, or just porting over the vectorization to NEON intrinsics.

**Comment by zeromus** [comment]
we don't need a separate ticket for every suggested optimization. chucking this elsewhere
