### ISSUE TITLE
[Linux/Ubuntu] Can't pass any CLI arguments to flatpak

### ISSUE THREAD

**Issue by itsonlyMiRE** [TASEmulators/desmume#513]
I'm on Ubuntu and running desmume with `flatpak run org.desmume.DeSmuME`. Trying to add any flags/arguments after this always results in `Unknown option --[option here]`.

Also, when I try launching a game thru CLI with `flatpak run org.desmume.DeSmuME "/path/to/nds/file.nds"`, the desmume window opens with a dialog box saying `"Unable to load: /path/to/nds/file.nds"`.

Let me know if more info needed.

EDIT: launching from CLI worked after I built from source. Why is the flatpak version the publicly advertised Linux version if it doesn't work properly?

**Comment by zeromus** [comment]
Sounds like a question for whoever added flatpak scripts, @linkmauve

**Comment by BubbyNX** [comment]
I am also having this issue.  The only workaround is opening DeSmuME, then going to File->Open and then manually finding the .nds but that starts to get tedious when I have to do it for every single game.

**Comment by intra0** [comment]
found the solution to the.
in the flatpack `finish-args` options, `--filesystem=host:ro` needs to be added.
1 line fix. made a pr on the flathub repository to fix it.

this issue can be closed now
