### ISSUE TITLE
Touchscreen specific question

### ISSUE THREAD

**Issue by sydbrig** [TASEmulators/desmume#514]
So, I checked the FAQ and it said that touchscreen/external hardware is low priority bug. I totally get that, but for my specific game (Rhythm heaven) I keep getting stuck between the issue of mouse latency or praying my pen works. It's off *just enough* to where I've reached a point where I cannot proceed because it requires incredibly precise clicking. My mouse is too slow, my touchpad is also slightly off, and I have to double-tap my pen/finger. It took me a couple of days to get past the intro because everything has to be exact.  Again, I understand that this is an isolated issue, but even when I use a metronome (the epitome of rhythm) to see if I can time it differently and still succeed, I've had no luck. Just wanted to know if that was an issue that's being looked at still or if I'm better off if I keep looking for ways around it.

**Comment by zeromus** [comment]
keep looking for ways around it.
