### ISSUE TITLE
Latest build doesnt work with both OpenGls enabled

### ISSUE THREAD

**Issue by Felipefpl** [TASEmulators/desmume#519]
I have win7 x64 and intel hd 2000, both are loaded successfully like it's displayed in the pic below (a pic of opengl old but it's the same with 3.2).

![Sem título](https://user-images.githubusercontent.com/5569804/161393675-fa3a1469-daab-481b-90fb-8f4c8c9f3310.gif)

If i load a rom with any of open gls enabled it crashes, softrasterizer is fine.

**Comment by zeromus** [comment]
intel HD graphics aren't supported. they're trash. upgrade or downgrade drivers.

**Comment by Jules-A** [comment]
I had this issue years ago, honestly back then those integrated Intel graphics were so useless you'd get better fps with software rasterizer even if it didn't crash...
