### ISSUE TITLE
High mouse polling rate causes extreme slowdown

### ISSUE THREAD

**Issue by Aqui1o** [TASEmulators/desmume#521]
Recreate using any mouse you can change the polling rate. The higher the polling rate, the more the emulation lags while moving the cursor across the screen. Excessive, rapid mouse movement also causes the audio buffer to be cleared repeatedly, as long as the mouse remains in motion. For notable results, compare 1000hz to 500hz to 250hz. 

Issue occurs on latest nightly and stable as of writing.  

For reference: I was using a mouse that has a default setting of 1000hz, Logitech G305

**Comment by rofl0r** [comment]
> Issue occurs on latest nightly and stable as of writing.

on which system ? usually the issue is that e.g. in SDL_PollEvent() loop, after every mouse move event the emulator is updated, rather than collecting all mouse move events into a single action. (e.g. discard all but the latest mouse move event, until an event of other type happens)

**Comment by zeromus** [comment]
can you people posting bugs obviously related to the frontend please write which OPERATING SYSTEM and DESMUME FRONTEND youre using?

**Comment by zeromus** [comment]
so... did you figure out what was wrong with your system, or what?
