### ISSUE TITLE
Windows Build VS2019

### ISSUE THREAD

**Issue by TrackDR** [TASEmulators/desmume#525]
Just downloaded the latest commit 07aefbd02c2285251539206a8ccb5738c21a60ff.
Tried to load desmume solution file in VS19 community edition which happened no problem.
When I try to build the solution with Release and x64, I get this error:

Build started...
1>------ Build started: Project: DeSmuME, Configuration: Release x64 ------
1>./defaultconfig/scmrev.h updated to 07aefbd0
1>Performing Custom Build Tools
1>Access is denied.
1>Access is denied.
1>Performing Custom Build Tools
1>Access is denied.
1>Access is denied.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'directx\directx.7z;lua\lua.7z' exited with code 1.
1>Done building project "DeSmuME.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by zeromus** [comment]
looks like your system administrator has barred you from running 7z.exe and touch.exe which is required by un7z_and_touch.bat which is how those .7z files are "built"

**Comment by TrackDR** [comment]
I didn't have touch.exe so I got it from here: https://sourceforge.net/projects/touchforwindows/
I changed the permissions on touch and 7z.

I changed un7z_and_touch.bat to 

C:\Users\me\Downloads\7z x -bd -y -o.libs %1
C:\Users\me\Downloads\touch %2 %3 %4 %5 %6 %7 %8 %9

I still get a 7b error though:

Build started...
1>------ Build started: Project: DeSmuME, Configuration: Release x64 ------
1>./defaultconfig/scmrev.h current at 07aefbd0
1>Performing Custom Build Tools
1>
1>7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
1>
1>Scanning the drive for archives:
1>1 file, 332412 bytes (325 KiB)
1>
1>Extracting archive: directx\directx.7z
1>--
1>Path = directx\directx.7z
1>Type = 7z
1>Physical Size = 332412
1>Headers Size = 251
1>Method = LZMA:22
1>Solid = +
1>Blocks = 1
1>
1>Everything is Ok
1>
1>Files: 3
1>Size:       4192064
1>Compressed: 332412
1>CUSTOMBUILD : Cannot open .libs\directx*. error : 7b
1>Performing Custom Build Tools
1>
1>7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
1>
1>Scanning the drive for archives:
1>1 file, 166260 bytes (163 KiB)
1>
1>Extracting archive: lua\lua.7z
1>--
1>Path = lua\lua.7z
1>Type = 7z
1>Physical Size = 166260
1>Headers Size = 324
1>Method = LZMA:768k BCJ2
1>Solid = +
1>Blocks = 2
1>
1>Everything is Ok
1>
1>Folders: 2
1>Files: 7
1>Size:       557170
1>Compressed: 166260
1>CUSTOMBUILD : Cannot open .libs\win32\lua*. error : 7b
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'directx\directx.7z;lua\lua.7z' exited with code 123.
1>Done building project "DeSmuME.vcxproj" -- FAILED.

**Comment by zeromus** [comment]
if you don't have touch, then you failed to download or clone desmume correctly. anything else could go wrong after that point. You need to find out why you're failing to download or clone desmume correctly. touch is in the repository.

**Comment by TrackDR** [comment]
I thought that these were not there in the repo since it was not working originally.
I set the permissions for every possible user to have "Full Control" (so modify, read, write, read&execute") on windows on touch.exe and 7z.exe in the repo.
I get this error:

1>------ Build started: Project: DeSmuME, Configuration: Release x64 ------
1>./defaultconfig/scmrev.h current at 07aefbd0
1>Performing Custom Build Tools
1>Access is denied.
1>Access is denied.
1>Performing Custom Build Tools
1>Access is denied.
1>Access is denied.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'directx\directx.7z;lua\lua.7z' exited with code 1.
1>Done building project "DeSmuME.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I then had to clear all the "Special Permissions" for every user for touch.exe and 7z.exe.
Then the build started to get past these problems, but still had some warnings and then was able to finish the build.

1>------ Build started: Project: DeSmuME, Configuration: Release x64 ------
1>./defaultconfig/scmrev.h current at 07aefbd0
1>Performing Custom Build Tools
1>Access is denied.
1>Performing Custom Build Tools
1>Access is denied.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "directx\directx.7z" succeeded, but specified output "f:\git-desmume\desmume-2022-05-13-181713\desmume\src\frontend\windows\.libs\directx.tag" has not been created. This may cause incremental build to work incorrectly.
1>slot1comp_mc.cpp
1>slot1comp_protocol.cpp
1>slot1comp_rom.cpp
1>slot1_retail_auto.cpp
1>slot1_retail_mcrom.cpp
1>slot1_retail_mcrom_debug.cpp
...
...
1>crc.cpp
1>directx-x64-ddraw-dinput8-dsound-dxerr8-dxguid.lib(dilib4.obj) : warning LNK4078: multiple '.text' sections found with different attributes (C0500040)
1>Generating code
1>Finished generating code
1>DeSmuME.vcxproj -> F:\git-desmume\desmume-2022-05-13-181713\desmume\src\frontend\windows\__bins\DeSmuME-VS2019-x64-Release.exe
1>Done building project "DeSmuME.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
