### ISSUE TITLE
Keyboard gets input DeSmuME doesn’t transfer it to game

### ISSUE THREAD

**Issue by Frootboops** [TASEmulators/desmume#526]
I was playing Pokémon Mystery Dungeon Sky, everything was perfectly fine, then literally out of nowhere at a random point my characters would not move. I could not click anything, no buttons would work. I checked to make sure inputs were still being made and lo and behold they were. The weirdest part is that controls work on other save states of this very play through, just not this most recent one. No clue what happened but it wasted twelve hours of my life so, not super stoked. I tried looking everything up I could online, deleting the ini file, nothing works.

**Comment by rofl0r** [comment]
i guess it could be helpful if you attach the savestate exposing this behaviour.

**Comment by zeromus** [comment]
The game state is corrputed due to accumulated errors from emulation, due to using an old desmume, or the jit, or maybe due to something that's not fixed yet. Stop using savestates. Save in-game frequently. Close the emulator and make backups of your .dsv files.
