### ISSUE TITLE
Homebrew detection improvements?

### ISSUE THREAD

**Issue by Aikku93** [TASEmulators/desmume#530]
[`GameInfo::isHomebrew()`](https://github.com/TASEmulators/desmume/blob/master/desmume/src/NDSSystem.cpp#L636) is currently checking for a very specific signature, and it's no longer even used by ndstool. This is causing issues when auto-patching DLDI, which makes things difficult when debugging applications that use it.

For the sake of backwards compatibility, it might be fine to keep this signature check in place, but perhaps also adding an additional check would be worthwhile (for example, ndstool is setting `header.gameCode == ####` by default).

**Comment by zeromus** [comment]
why weren't we ever using a specific maker code, or something like that?
can we add #### as a new check and keep the old signature check too?

**Comment by Aikku93** [comment]
Yeah, I really wish we'd standardized some way to signal homebrew (my personal preference would've been to set bit7 of Header.Unitcode).

Adding a check for #### is easy done. I mostly opened this as an issue instead of a PR to see if anyone has any better ideas I hadn't thought of.

**Comment by zeromus** [comment]
I doubt anyone's going to chime in with anything else. You've clearly thought about this more than anyone else has. The resolution seems sensible.

**Comment by Aikku93** [comment]
I've created pull request #532 to fix this (I thought I'd already commented when I did that >_< My bad). Minimally invasive, just a single extra check added.
