### ISSUE TITLE
Linux CLI - GBA Slot SRAM Path is not configured correctly

### ISSUE THREAD

**Issue by colton5007** [TASEmulators/desmume#536]
It appears there is an error in how the Linux CLI assigns the value to the `GBACartridge_SRAMPath` variable in the main.cpp file (`desmume/src/frontend/posix/cli/main.cpp` lines 392 and 395 on the master branch). Although, since there is no documentation on the desired naming scheme for the `.sav` file, this may be intended-- in which case, I apologize for the needless issue. Nonetheless, I think it would be helpful for this to be documented either in the code or in the `desmume --help` menu.

As it stands, the SRAM Path's value is set with 

`GBACartridge_SRAMPath = strright(GBACartridge_RomPath,4) + ".sav";` 

which occurs on lines 392 and 395. If the ROM path is `gamerom.gba` the corresponding SRAM file should be `gamerom.sav`. But currently for the ROM `gamerom.gba`, the SRAM Path will be set as `.gba.sav`. One fix for this would be to do a simple substring,

`GBACartridge_SRAMPath = GBACartridge_RomPath.substring(0, GBACartridge_RomPath.size() - 4) + ".sav";`

so that it effectively replaces `.rom` in the ROM path with `.sav`. I believe most GBA emulators use this naming convention for the SRAM file. It appears that there is not an implemented way of handling ROMs with a different extension than `.gba`, so line 395 may need a different modification. Given that this is an edge case (and any one solution would almost surely not make everyone happy), I would defer such changes to the project's developers.

Normally, I would make this a PR, but it is such a minor change, and I am not 100% sure if the current implementation is not the desired behavior. Moreover, since string manipulation is always a sensitive topic, I did not want to upset any of the fine developers of the desmume project by making PRs that do not satisfy any coding conventions that I am unaware of.

**Comment by zeromus** [comment]
it's obviously meant to work the way you want it to, send a PR
