### ISSUE TITLE
Windows : Shut Up function does not works.

### ISSUE THREAD

**Issue by lemaximedu66** [TASEmulators/desmume#549]
when i click "Shut Up" (really funny option) nothing happens (even in the console).

**Comment by zeromus** [comment]
It only works on the dual spu sync/async mode

**Comment by lemaximedu66** [comment]
i don't understand.

**Comment by zeromus** [comment]
config > sound > synchronization mode

**Comment by lemaximedu66** [comment]
oh ok thanks. didn't know about that until now ! thanks again.
