### ISSUE TITLE
Desmume 0.9.13 can't be built on ppc64le

### ISSUE THREAD

**Issue by musuruan** [TASEmulators/desmume#550]
Hi. I was updating the RPM Fusion package and I found out that desmume 0.9.13 cannot be built on ppc64le.

There are a bunch of:
`error: ‘vector’ does not name a type; did you mean ‘vec_or’?`

Here you can find a build log:
https://koji.rpmfusion.org/kojifiles/work/tasks/7991/547991/build.log

**Comment by rofl0r** [comment]
relevant part from log:
```
g++ -Ilibdesmume.a.p -I. -I.. -I../../../../src -I../../../../src/libretro-common/include -I../../../../src/frontend -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/SDL2 -I/usr/include/AL -I/usr/include/soundtouch -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O0 -DHAVE_LIBSOUNDTOUCH -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -fPIC -DTIXML_USE_STL=YES -pthread -D_REENTRANT -MD -MQ libdesmume.a.p/.._.._armcpu.cpp.o -MF libdesmume.a.p/.._.._armcpu.cpp.o.d -o libdesmume.a.p/.._.._armcpu.cpp.o -c ../../../armcpu.cpp
In file included from ../../../armcpu.h:26,
                 from ../../../armcpu.cpp:24:
../../../types.h:265:9: error: ‘vector’ does not name a type; did you mean ‘vec_or’?
  265 | typedef vector unsigned char v128u8;
      |         ^~~~~~
      |         vec_or
../../../types.h:266:9: error: ‘vector’ does not name a type; did you mean ‘vec_or’?
  266 | typedef vector signed char v128s8;
      |         ^~~~~~
      |         vec_or
```

**Comment by rogerman** [comment]
The use of vector is correct. ppc64le is not currently supported -- only ppc and ppc64 (big-endian) are supported as of this writing.

Someone else will have to work on ppc64le support, as I have no means of testing this.

**Comment by rogerman** [comment]
Since the only area of failure is with the AltiVec stuff, I've made commit a95e4c57 as a band-aid fix for ppcle/ppc64le. These architectures won't use AltiVec anymore (because our AltiVec code only supports big-endian right now), but instead fall back to the standard C code paths.

**Comment by musuruan** [comment]
It's not enough to have a successful build:
https://koji.rpmfusion.org/kojifiles/work/tasks/8078/548078/build.log

**Comment by rogerman** [comment]
Try commit d4afd497.

**Comment by musuruan** [comment]
Thank you. Now it builds on all RPM Fusion supported architectures:
https://koji.rpmfusion.org/koji/taskinfo?taskID=548178
