### ISSUE TITLE
Desmume 0.9.13 can't be built on aarch64

### ISSUE THREAD

**Issue by musuruan** [TASEmulators/desmume#551]
Hi. I was updating the RPM Fusion package and I found out that desmume 0.9.13 cannot be built on aarch64.

There is the following error:
```
../../../render3D.cpp:902:49: error: cannot convert ‘uint16x8_t’ to ‘uint8x16_t’
  902 |                 vst1q_u8( outFog + i, vuzp1q_u16(vshrq_n_u16(clearDepth.val[0], 15), vshrq_n_u16(clearDepth.val[1], 15)) );
      |                                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 uint16x8_t

```

Here you can find a build log:
https://koji.rpmfusion.org/kojifiles/work/tasks/7992/547992/build.log

**Comment by rogerman** [comment]
This issue was already addressed in commit 24eb5ed9.

You are using an old version of the code. Update to commit 24eb5ed9 and try again.
