### ISSUE TITLE
Fix format strings

### ISSUE THREAD

**Issue by musuruan** [TASEmulators/desmume#552]
Hi. I was updating the RPM Fusion package and to build under x86_64 I had to fix these security issues:
https://pkgs.rpmfusion.org/cgit/free/desmume.git/tree/desmume-0.9.13-formatstring.patch

Packages in Fedora are compiled with  -Werror=format-security:
https://fedoraproject.org/wiki/Format-Security-FAQ

You may want to include this patch upstream.

**Comment by zeromus** [comment]
What a stupid warning. What a stupider error. Fortunately the impact on the code is minimal so I'll accept a patch without grumbling any further; I suppose there are a lot stupider errors with a lot noisier resolution

**Comment by rofl0r** [comment]
the first hunk of that patch looks bogus though, as it will cripple the functionality of printerror

**Comment by zeromus** [comment]
haha! good catch!
