### ISSUE TITLE
Ranger: Shadows of Almia tile accuracy

### ISSUE THREAD

**Issue by DirtyDane** [TASEmulators/desmume#555]
Tiles are rendered being placed off by one pixel on average for the majority of the environments. This creates weird gaps in visuals. 
Running on 0.9.13 lowering resolution helps. but does not resolve

**Comment by DirtyDane** [comment]
those are the current settings I'm using.

**Comment by zeromus** [comment]
Then turn off hack and/or change to opengl

**Comment by DirtyDane** [comment]
that makes it worse..

**Comment by DirtyDane** [comment]
if it helps is there a set of information I can give you? I have it to a point where it only has problems below where the character sprite is rendered.

**Comment by zeromus** [comment]
no, nothing you can do helps. issue already filed:
https://github.com/TASEmulators/desmume/issues/189

**Comment by DirtyDane** [comment]
Thank you! appreciate the quick and to the point assistance!

**Comment by zeromus** [comment]
You could also try using melonds
