### ISSUE TITLE
Possible mismatch of buffer sizes

### ISSUE THREAD

**Issue by janisozaur** [TASEmulators/desmume#563]
A recent commit, 677c6bb90754d00842, changed how buffers are handled, but there is still possibility of a bug due to mismatched sizes passed to `memcpy`:

https://github.com/TASEmulators/desmume/blob/677c6bb90754d008428005e3d31a038a78c79695/desmume/src/frontend/posix/gtk/main.cpp#L1943

and later in that same function:

https://github.com/TASEmulators/desmume/blob/677c6bb90754d008428005e3d31a038a78c79695/desmume/src/frontend/posix/gtk/main.cpp#L1964

Can you please confirm?

**Comment by rofl0r** [comment]
confirmed, c68cc14f16e9709361ecac73b217ba2588ed7990 changed size of keyboard_cfg, but not joypad_cfg...

we should probably have a static assert there that makes sure both arrays have the same sizeof
