### ISSUE TITLE
Desktop Files For Desmume

### ISSUE THREAD

**Issue by marcelocripe** [TASEmulators/desmume#570]
Hello dear developers.

Please accept the desmume.desktop file containing the texts in Brazilian Portuguese.
I ask you to make the texts of the .desktop file available directly with the programming code, so that all GNU/Linux distributions will benefit from the translations of the Name[pt_BR], Comment[pt_BR] and Keywords[pt_BR] entries. Hopefully other volunteer translators will be able to contribute their translations into multiple languages.

The .desktop file is responsible for displaying the texts in the menus and in the operating system's application search programs.

Also, if programmers are interested, we can translate Desmume's graphical interface.

I thank you for creating and maintaining the Desmume game emulator.

marcelocripe
(Original text in Brazilian Portuguese)

- - - - -

Olá prezados desenvoveldores.

Por favor, aceitem o arquivo desmume.desktop contendo os textos em idioma Português do Brasil.
Eu peço para vocês que disponibilizem diretamente com o código de programação os textos do arquivo .desktop, assim todas as distribuições GNU/Linux serão beneficidas com as traduções das entradas Name[pt_BR], Comment[pt_BR] e Keywords[pt_BR]. Esperançosamente outros tradutores voluntários poderão contribuir com as suas traduções para vários idiomas.

O arquivo .desktop é responsável por exibir os textos dos menus e nos programas de busca de aplicativos do sistema operacional.

E ainda, se houver o interesse dos programadores, poderemos traduzir a interface gráfica do Desmume.

Eu agradeço por criarem e manterem o emulador de jogos Desmume.

marcelocripe
(Texto original em idioma Português do Brasil)
[Desktop Files.zip](https://github.com/TASEmulators/desmume/files/9169904/Desktop.Files.zip)

**Comment by zeromus** [comment]
why is there a glade file with redundant contents

**Comment by marcelocripe** [comment]
"why is there a glade file with redundant contents"
Yes, I know it's redundant. What I don't know is why the "desmume-glade.desktop" file is in the Debian 0.9.11-3 package. It was in this Debian 11 package that I found these two .desktop files. As I don't know which one will be used, I decided to send both.
Thank you very much for all your attention on the Desmume forum.

- - - - -

"why is there a glade file with redundant contents"
Sim, eu sei que é redundante. O que eu não sei é por qual motivo o arquivo "desmume-glade.desktop" está no pacote 0.9.11-3 do Debian. Foi neste pacote do Debian 11 que eu encontrei estes dois arquivos .desktop. Como eu não sei qual dos dois será utilizado, eu resolvi enviar os dois.
Muito obrigado por toda a sua atenção no fórum do Desmume.

**Comment by zeromus** [comment]
Well, I dont know which one will be used either.
This is why we leave it up to an EXPERT
If I ever see someone add a desktop file, I'll remember to tell them there's a brazilian translation here

**Comment by marcelocripe** [comment]
Dear zeromus.

The file "desmume.desktop" received the language translation it and it_IT made by Spartak77, kindly provided on 08-17-2022. The Spartak77 is one of the volunteer translators for the Italian antiX community team.

We now have 3 languages.

- - - - -

Prezado zeromus.

O arquivo "desmume.desktop" recebeu a tradução do idioma it e it_IT feita pelo Spartak77, gentilmente fornecida no dia 17-08-2022. O Spartak77 é um dos tradutores voluntários da equipe italiana da comunidade antiX.

Agora temos 3 idiomas.

**Comment by rofl0r** [comment]
i vote for leaving translations of desktop files, which seems kinda silly anyway as it's only a single phrase like "NDS emulator", to distros that want to support it.
once you get into the translation business as a developer, you'll be overwhelmed by translation addition/changes PRs, which you need to review, and need to carefully plan each and every single change of any piece of text in the application in order not to break translations. not to talk about the spam in the commit history.

**Comment by zeromus** [comment]
In general I agree about the maintenance hazards of localizations (in fact we've already nuked them from desmume) but this may be a special case since it's pretty trivial cosmetic stuff. Still, I have no intention of committing this. Only an actually on-staff linux maintainer should do it.

**Comment by marcelocripe** [comment]
So who is this "Only an actually on-staff linux maintainer should do it."?

The translation of programs ensures communication between programmers and the end user.
We would have the translations of the languages that there were people interested in being volunteer translators. If there are native speakers of languages other than English on the DeSmuME development team, these people can help with translations if they wish to do so.
I'd like to be able to help translate the "desmume.desktop" file and the DeSmuME GUI.

- - - - -

Então quem seria este "Only an actually on-staff linux maintainer should do it."?

A tradução dos programas garantem a comunicação entre os programadores e o usuário final.
Nós teríamos as traduções dos idiomas que houvessem pessoas interessadas em serem tradutores voluntários. Se na equipe de desenvolvimento do DeSmuME houver nativos de idiomas diferentes do Inglês, estas pessoas poderão ajudar com as traduções se assim desejarem fazer.
Eu gostaria de poder ajudar a traduzir arquivo "desmume.desktop" e a interface gráfica do DeSmuME.

**Comment by zeromus** [comment]
There is no actually on-staff linux maintainer. This individual is needed to answer questions like "why is there a glade file with redundant contents"

**Comment by marcelocripe** [comment]
"There is no actually on-staff linux maintainer. This individual is needed to answer questions like "why is there a glade file with redundant contents"
I also don't know why in the package "desmume_0.9.11-3_amd64.deb" that is available on the page https://ftp.debian.org/debian/pool/main/d/desmume/ there is "desmume.desktop" and the " desmume-glade.desktop".
In the package control file "desmume_0.9.11-3_amd64.deb" it indicates the maintainer as being a "team" (Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>).

What I know happens is the following, if the source code does not have a .desktop file for the program, whoever creates the package for the distribution will need to create a .desktop file, otherwise the respective program will not be displayed in the menu. If the .desktop file is available with the program's source code, all packagers will use the texts from the .desktop file. If eventually some distribution has quirks that require changes to the .desktop file, it will be much easier for the packager to edit the .desktop file than having to create a .desktop file for each distribution.

Something interesting that I was able to identify is that in programs that do not provide a .desktop file, for each GNU/Linux distribution, we can find .desktop files with more or less translations, some without translation, other .desktop files have one or two languages , in addition to an exhaustive and endless rework on the part of the translators of locating the packager of the distribution, instead of identifying the developer of the program to offer their translations voluntarily.

I think that the translations need to be closer and closer to the source code, because everyone will benefit. What's the point if I translate a DeSmuME .desktop file for use only on antiX Linux, if I can translate the .desktop file and the DeSmuME GUI, all distributions will benefit and less work will be required from packagers and translators for each GNU/Linux distribution.

Another example, if I translate all antiX Linux locally and these translations never reach the source code of each of the programs, in the next update of these programs, all local translations will be lost, the untranslated .desktop file will replace my file .desktop that contains the translations.

- - - - -

"There is no actually on-staff linux maintainer. This individual is needed to answer questions like "why is there a glade file with redundant contents"
Eu também não sei porque no pacote "desmume_0.9.11-3_amd64.deb" que é disponibilizado na página https://ftp.debian.org/debian/pool/main/d/desmume/ existe "desmume.desktop" e o "desmume-glade.desktop".
No arquivo de controle do pacote "desmume_0.9.11-3_amd64.deb" indica o mantenedor como sendo uma "equipe" (Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>).

O que eu sei que acontece é o seguinte, se no código fonte não existe um arquivo .desktop do programa, quem for criar o pacote para a distribuição precisará criar um arquivo .desktop, caso contrário não será exibido no menu o respectivo programa. Se o arquivo .desktop está disponível com o código fonte do programa, todos os empacotadores irão utilizar os textos do arquivo .desktop. Se eventualmente alguma distribuição possui peculiariedades que exigem alterações no arquivo .desktop, será muito mais fácil para o empacotar editar o arquivo .desktop do que ter que criar um arquivo .desktop para cada distribuição.

Algo interessante que eu consegui identificar é que nos programas que não fornecem um arquivo .desktop, para cada distribuição GNU/Linux, podemos encontrar os arquivos .desktop com mais ou menos traduções, alguns sem tradução, outros arquivos .desktop possuem um ou dois idiomas, além de um retrabalho exaustivo e sem fim por parte dos tradutores de localizar o empacotador da distribuição, ao invés de identificar o desenvolvedor do programa para oferecer as suas traduções de forma voluntária.

Eu penso que as traduções precisam estar cada vez mais próximas do código fonte, pois todas as pessoas serão beneficiadas. De que adianta se eu traduzir um arquivo .desktop do DeSmuME para ser utilizado apenas no antiX Linux, se eu puder traduzir o arquivo .desktop e a interface gráfica do DeSmuME, todas as distribuições serão beneficiadas e menos trabalhos serão exigidos dos empacotadores e dos tradutores por cada distribuição GNU/Linux.

Um outro exemplo, se eu traduzir todo o antiX Linux localmente e estas traduções nunca chegarem até o código fonte de cada um dos programas, na próxima atualização destes programas, todas as traduções locais serão perdidas, o arquivo .desktop sem tradução substituirá o meu arquivo .desktop local que contém as traduções.

**Comment by zeromus** [comment]
You don't have to convince me that it's good to have the desktop files in the source code. The problem is we don't have anyone qualified to PUT it it in the source code. You don't understand the technical details, you just write some translated strings and slop the files over here. Wait for a linux maintainer to show up. It seems like you found the maintainer of the packages you care about as "debian games team". Go bother them.
