### ISSUE TITLE
General Question: Texture Scaling

### ISSUE THREAD

**Issue by AudioDuplication** [TASEmulators/desmume#576]
I was just wondering, 
![image](https://user-images.githubusercontent.com/108935890/183220099-126157db-3200-4e49-955c-87acf0fc37ab.png)

The "Texture scaling" option in the 3D options menu, what type of upscaling does it use? Is it HQx or xBRZ? I am asking because I like the results is produces and would like to use the same scaling method elsewhere.

**Comment by zeromus** [comment]
xBRZ
