### ISSUE TITLE
Early Access Code 

### ISSUE THREAD

**Issue by Bobby926** [TASEmulators/desmume#579]
After reloading the DS Emulator to my Home Screen the Early Access was gone.
Gab someone help? New Code??

**Comment by Bobby926** [comment]
So i gues this means no Early Access and no Turbo Mode for me anymore

**Comment by zeromus** [comment]
I have no clue what you're talking about. You're on the wrong project. We don't have "Early Access" or "Turbo Mode". perhaps you mean to address your complaints to somebody else selling desmume in another package.
