### ISSUE TITLE
WinPcap or Npcap ? WinPcap it's not anymore in development..... 

### ISSUE THREAD

**Issue by DjDiabolik** [TASEmulators/desmume#580]
......instead it's suggested to use/install NpCap but this is works whit DeSmuME ?

**Comment by zeromus** [comment]
So what? Use winpcap anyway. We don't support wifi here, though.

**Comment by DjDiabolik** [comment]
WinPcap it's not works on windows 10...... infact i have install and it's not work.

**Comment by zeromus** [comment]
npcap is supposed to be compatible. Only someone who knows how to use wifi on desmume could decide that because only they would know how to make wifi work on desmume in the first place. we don't know how to do that. we don't support wifi.
