### ISSUE TITLE
[Win10] Cannot use in-game saves when using the record movie feature

### ISSUE THREAD

**Issue by lowendgamer** [TASEmulators/desmume#584]
Playing dragon quest iv on desmume, but when using the record movie feature it won't save. Using version 0.9.11-x64
It shows "The save log could not be saved. Please turn the power OFF and reinsert DS Game Card."

I'm practicing a speedrun so I refrain from using savestates.

**Comment by zeromus** [comment]
years-old version is not supported. try 0.9.13. then we can talk.
