### ISSUE TITLE
Spectrobes Into Stuck DS emu

### ISSUE THREAD

**Issue by Scoot738** [TASEmulators/desmume#586]
Stuck on the very first dialogue screen for Spectrobes on the DS emulator.

**Comment by zeromus** [comment]
press a button instead of tapping.

**Comment by Scoot738** [comment]
pressing a button obviously doesn't work either...

**Comment by zeromus** [comment]
I tried it myself and it worked. Thousands or possibly even millions of NDS emulator users are confused about when they have to tap and when they have to press buttons. In this game I noticed you have to tap first and then without prompting, you have to press buttons or else you will be "stuck in the very first dialogue screen".
