### ISSUE TITLE
"Main Screen First Duplication / Bug"

### ISSUE THREAD

**Issue by ZxCFss** [TASEmulators/desmume#587]
Setting "View -> LCDs Layout -> Main screen first" caused duplication / bug to some games.
The games i tested and encountered the duplication / bug was
1. Final Fantasy - The 4 Heroes of Light (Minor not affecting gameplay)
2. Ninokuni - Shikkoku no Madoushi (Serious and affecting gameplay)
3. Etrian Odyssey (Minor not affecting gameplay)

Uploaded the video to show how it looks like on youtube since the files size is bigger than 10MB.
https://www.youtube.com/playlist?list=PLZ1XqsShP2UP6elKUPg8kmZlDtxK0B-SQ

**Comment by zeromus** [comment]
This is proper behavior for "main screen first". If you don't like it, don't use that option.
