### ISSUE TITLE
Advance Wars Dual Strike - CHECK image not displaying correctly.

### ISSUE THREAD

**Issue by radioshadow** [TASEmulators/desmume#594]
In the first Normal Campaign mission, after you start capturing the City, the CHECK graphic appears. The emulator doesn't seem to display this correctly (like some of the pixels are not in line). See image below:
https://i.ibb.co/2kqtqQm/AWDS-CHECK-Issue.png

**Comment by zeromus** [comment]
config > 3d settings > 3d rendering engine
config > 3d settings > enable TXT hack
