### ISSUE TITLE
Advance Wars Dual Strike - Crashes when returning from DOWNLOAD 

### ISSUE THREAD

**Issue by radioshadow** [TASEmulators/desmume#595]
If you click WIRELESS > DOWNLOAD, and then click BACK, the game gets stuck on a black screen:
https://i.ibb.co/hDHX9jB/AWDS-Crash.png
https://i.ibb.co/2ZrmW8S/AWDS-Crash-2.png

**Comment by zeromus** [comment]
desmume doesn't support wifi.
