### ISSUE TITLE
view issue

### ISSUE THREAD

**Issue by kacperineusz** [TASEmulators/desmume#598]
Hi, Today i installed desmume 0.9.13 and have view issue. During the game i can see miniature of the main view. Miniature is on the left in vertical layout and on top in horizontal layout. I changed various settings, including ,, the show toolbar'' setting, but it doesn't change anything, even after restarting. It is random moment when it finally disappears.

**Comment by kacperineusz** [comment]
![Zrzut ekranu (6)](https://user-images.githubusercontent.com/91287624/195879092-af25bd62-76c3-4c6e-866d-890cd412c643.png)
![Zrzut ekranu (7)](https://user-images.githubusercontent.com/91287624/195879186-54b605c9-f1d1-456f-8579-f86b4fb17f6b.png)

**Comment by zeromus** [comment]
config > display method

**Comment by kacperineusz** [comment]
> config > display method

in Display method i have ,,Direct Draw HW'' What should i change ?

**Comment by zeromus** [comment]
Are you kidding? Change it to what makes it work.
