### ISSUE TITLE
Blaze Black freezed

### ISSUE THREAD

**Issue by Chlaferno** [TASEmulators/desmume#601]
Hello,
I´m currently playing a pokemon blaze black run. I entered a trainer battle and the game freezed. I can still hear the normal music but I´m stuck at the start screen of the battle. Any ideas how i can fix that?
![Bild_2022-10-23_134423385](https://user-images.githubusercontent.com/116493776/197390171-3ac2bc79-4606-4db2-81f5-2eecc9dce818.png)

**Comment by zeromus** [comment]
Hacked roms are buggy sometimes.
