### ISSUE TITLE
Proposal for an event hosted by the University of Seville

### ISSUE THREAD

**Issue by alegestor** [TASEmulators/desmume#605]
Hello, I was interested in contacting you with a proposal to talk in an event held by the University of Seville. Since I was not able to find the contact info in the main page I would kindly ask for a way to formally contact you with this purpose.

Thank you.

**Comment by zeromus** [comment]
Sorry, none of us are celebrities or give speeches. You should focus on emulator programmers who blab on social media a bunch. The mame developers are way more famous and communicative than us, not to mention numerous; you should try them. There are also people doing emulation releases of commercial products who stand to benefit financially from self-promotion and so do a lot of it, albeit it's all marketing hot air so anything they have to say is of a different character than what you'd get from a programmer.
