### ISSUE TITLE
i cant play my downloaded rom's in my DeSmuME :(

### ISSUE THREAD

**Issue by computerplays69** [TASEmulators/desmume#608]
i was going to church with my dad and after church we went home. so i started up my pc blah blah blah. so i opened DeSmuME and use a rom of pokemon black and white version 2 and it didnt work. i tried other roms but didnt work eventually i reopened DeSmuME once again and tried to use a rom but didnt work again. PLS TELL ME WHY I CANT PLAY MY DOWNLOADED ROMS IN MY COPY OF DESMUME?

**Comment by zeromus** [comment]
The strange way you worded this makes it sound like it worked perfectly fine for (?? period of time) and then one day for absolutely no reason, I wasn't even in my house at the time, suddenly it stopped working. But you don't come right out and say that. Please explain more precisely.
