### ISSUE TITLE
I CAN'T PLAY MY DESMUME

### ISSUE THREAD

**Issue by Oliveira363** [TASEmulators/desmume#609]
first i would like to say that i am using google translator.

my desmume gets a black screen every time i start a game

Yesterday I pressed several random buttons but I could still play, so I didn't care. I changed some buttons to improve the graphics, but I already put them in normal, but it doesn't enter my games anymore, it always gives a black screen when I start, I've already tried to uninstall and install again, but the error persists, I've tried download an old version, but the bug persists.

I noticed that the settings are still the same in past versions.

I really don't know what to do, I believe it's a problem with the settings, but I'm not sure.

OBS: the games worked before

**Comment by Oliveira363** [comment]
Note: I can hear the game, but the screen is black

**Comment by Oliveira363** [comment]
one more note: I watched a youtube video and fixed some settings, but the game still gives a black screen

**Comment by zeromus** [comment]
config > display method
