### ISSUE TITLE
White Screen(No video) But i have audio 

### ISSUE THREAD

**Issue by MysticcMB** [TASEmulators/desmume#611]
So hum, i was plating pokemon soulsivler yesterday and everyting was working perfectly but today when i opened up my Desmume and launched the ROM (Pokemon soulsilver), i cannot see nothing(Nothing appears, it's a whtie screen), like i got the audio and all my saved state are there but i juste cannot have the image...can someone helped me ? I never go into setting and shit so i dont know what happened...

**Comment by MysticcMB** [comment]
Other rom are doing the same thing too.

**Comment by zeromus** [comment]
change config > display method
