### ISSUE TITLE
Black 2 PC freeze

### ISSUE THREAD

**Issue by Kachowskien** [TASEmulators/desmume#614]
In Pokemon Black 2 when I try to withdraw a Pokemon from the box the game will crash making me unable to use it on the emulator

**Comment by zeromus** [comment]
Aren't pokemons in boxes transferred via wifi?

**Comment by Kachowskien** [comment]
> Aren't pokemons in boxes transferred via wifi?

No I don't think so.

**Comment by zeromus** [comment]
What's the significance of pokemons in boxes? I can't even find reference to pokemons in boxes on gamefaqs, only medal boxes and textboxes

**Comment by Kachowskien** [comment]
> 

It is the PC, for adding and removing Party Pokemon

**Comment by zeromus** [comment]
Are you saying that the elementary function of picking which six pokemon you bring into battle doesn't work? Impossible. You can find 1000s of videos of people playing this game on desmume. Perhaps youve HACKED or CHEATED. You should also use the latest version of desmume (most people aren't) and you should also stop using savestates (most people are) but rather use in-game saves only.
