### ISSUE TITLE
[windows]Garbled error in Japanese save name

### ISSUE THREAD

**Issue by tanatana9999** [TASEmulators/desmume#615]
In 0.9.11, I was able to save in Japanese, but in 0.9.13, when I save in Japanese, the characters are garbled and I cannot create save data. can it be improved?

**Comment by zeromus** [comment]
I don't understand "save in Japanese"

**Comment by tanatana9999** [comment]
In 0.9.13, Japanese cannot be used for "Save state as...". For the time being, I will use 0.9.11, which can use Japanese.

**Comment by zeromus** [comment]
OK, if writing the names of files in Japanese is so important to you then that's a great idea for a workaround.
