### ISSUE TITLE
touch screen wont work

### ISSUE THREAD

**Issue by med280gg** [TASEmulators/desmume#616]
when i try click on stuff with my mouse for touch screen it wont work
how do i fix?

**Comment by zeromus** [comment]
stop using external firmware file.

**Comment by med280gg** [comment]
> 

how do i do that

**Comment by zeromus** [comment]
do the opposite of whatever you did to start using external firmware file in the first place. config > emulation settings

**Comment by med280gg** [comment]
> do the opposite of whatever you did to start using external firmware file in the first place. config > emulation settings

i did that and it didnt work, might uninstall and redownload
