### ISSUE TITLE
Program crashes when saving states

### ISSUE THREAD

**Issue by MrNobody1023** [TASEmulators/desmume#617]
I was playing Pokemon Black 2 when I found one of the legendary Pokémon. I did some soft resets when I finally found it. However, when I tried to save a state the program crashed. After this encounter, Desnume keeps crashing when quick-saving a state, but loads it just fine

**Comment by zeromus** [comment]
So you're telling me you have a savestate, such that when you load it, you can no longer immediately turn around and save it again?

**Comment by zeromus** [comment]
we''re working on fixing this stuff now
