### ISSUE TITLE
Game crashes after I try to load saves from files

### ISSUE THREAD

**Issue by Avnerr12** [TASEmulators/desmume#622]
I was playing through Black 2, and I made it to the Ghetsis fight and stopped after I beat it to go to bed one night. When I went to play again, the game would crash every time I tried to load the file. It is still doing this, and I am unsure of how to fix it.

**Comment by zeromus** [comment]
Load the file -- how? Which version of desmume?

**Comment by Avnerr12** [comment]
I have a save that I keep in my files that I just click to open.  The version is 0.9.13

**Comment by zeromus** [comment]
You mean you have a savestate you keep in your files that you just click to open. How do you create the save state?

**Comment by Avnerr12** [comment]
Yes. I create the save state by using "save as"

**Comment by zeromus** [comment]
Please attach that save state

**Comment by Avnerr12** [comment]
It won't let me attach the file

**Comment by zeromus** [comment]
You must rename it to .png and zip it or find any other way you want to upload a file on the internet, there are thousands of ways

**Comment by Avnerr12** [comment]
[Saves.zip](https://github.com/TASEmulators/desmume/files/10442251/Saves.zip)

**Comment by zeromus** [comment]
fixed by 8438a5a6478879612acca108ec800c49e53916f2

**Comment by zeromus** [comment]
http://desmume.org/download/
"Nightly builds for the windows version can be found here"
