### ISSUE TITLE
Crash when using opengl old or opengl 3.2

### ISSUE THREAD

**Issue by Felipefpl** [TASEmulators/desmume#630]
Desmume crashes when loading a rom in any of the opengl modes i use, i attached pics made with both enabled to show the logs:

OpenGL Old
![Old](https://user-images.githubusercontent.com/5569804/216383008-4bafb915-9eeb-422e-92e2-308114eb1b3b.gif)

OpenGL 3.2
![3](https://user-images.githubusercontent.com/5569804/216383067-73406414-246e-4c9f-b6df-c566f68606d3.gif)

I have an intel HD 2000, it's an old/bad card, i know, but it should work at least with opengl old. With opengl 3.2 the emu should at least display a msg saying: "OpenGL 3.2 wont work with your video card, now Desmume will close. Please choose Software Rasterizer or OpenGL Old to run your games".

**Comment by zeromus** [comment]
Not worth the time. Sometimes opengl drivers as soon as we touch them, before we can even find out anything about what drivers they are. If you can install visual studio, clone the code, and debug there, then we might investigate why its crashing.

**Comment by Jules-A** [comment]
>I have an intel HD 2000
Desmume has been crashing on that ancient iGPU for years but at this point it's not worth considering and honestly even if it did work on it, it's so weak that software would probably give higher FPS anyway.
