### ISSUE TITLE
Bug in Olivine City

### ISSUE THREAD

**Issue by TRISKKEET** [TASEmulators/desmume#636]
as soon as i get ready to walk past the gym in olivine the doors open and freezes my game. i cannot progress

**Comment by Felipefpl** [comment]
No savegame to help the devs?

**Comment by TRISKKEET** [comment]
wdym by that

**Comment by TRISKKEET** [comment]
> No savegame to help the devs?

wdym

**Comment by zeromus** [comment]
stop using savestates. save in-game frequently, close the emulator, open it again, and load from your in-game save.

also this shouldnt be happening on versions of the emulator from the past few years, perhaps you are using ancient version

**Comment by TRISKKEET** [comment]
> stop using savestates. save in-game frequently, close the emulator, open it again, and load from your in-game save.
> 
> also this shouldnt be happening on versions of the emulator from the past few years, perhaps you are using ancient version

I exported my save data and downloaded a new rom its working good now. I dont use savestates i sue the in game save

**Comment by zeromus** [comment]
If you werent using savestates and _those steps_ fixed _that problem_ then you were using cheats and left a bad one stuck on, or changed the JIT speed options. It's the only other thing that can make the game freeze.

**Comment by TRISKKEET** [comment]
I don’t use cheats. What is JIT?

**Comment by zeromus** [comment]
config > emulation settings > "use dynamic recompiler" > block size
maybe your kid brother changed something when he sneaked on your computer.
i guess it's also possible a file from your old install became corrupted.
it's just really strange for those steps to fix that problem, without some other user error being involved, so you may want to retrace your steps or keep the old directories around to scrutinize them closely and compare, or else the same problem may happen again
