### ISSUE TITLE
GPU Scaling factor not working together with Magnification filter

### ISSUE THREAD

**Issue by LuismaSP89** [TASEmulators/desmume#639]
Both options are not working together, If I usually have enabled 5xbrz filter, but if I select a GPU scaling factor "It doesn't matter if 2, 3, 4, etc" the magnification filter is automatically disabled. I tested also with other filters but the result is the same.

I know having both options together are a GPU killer, but for those who have a strong enough GPU this will be a good option to have. I don't know if this is a bug or it's the way it works, but other emulators are capable to increase 3D internal resolution and setting also a screen filter like the xbrz together and looks beautiful.

My specs:

i7 4790k
16GB DDR3
GTX 970
Windows 11

Using latest Desmume stable version "0.9.13"

**Comment by zeromus** [comment]
It works. Perhaps you're not noticing it because the GPU scaling prescales the 2d pixels so much that it's hard for BRZ etc to get a grip on them. take some screenshots with BRZ enabled and disabled and compare them closely.
