### ISSUE TITLE
Missing drawing.

### ISSUE THREAD

**Issue by damil42** [TASEmulators/desmume#642]
There is a bug in drawing lines or layer? I don't know, but take a look to the screenshots:

| DeSmuME | MelonDS |
| --- | --- |
| ![DeSmuME](https://user-images.githubusercontent.com/126908176/222797737-215f8a6e-a13a-4354-957c-5cffc0eb4701.png) | ![MelonDS](https://user-images.githubusercontent.com/126908176/222797739-30b490d1-5666-4eec-9d39-e3d77cd0a144.png) |
| The range lines are not drawn. Btw. the image appears a bit more blurry then on MelonDS.|The range lines are drawn and the image is sharper. But with some missing pixels appearing in magenta or red.|

Game: Anno 1701 on the latest core for RetroArch. I tried a lot of options. Nothing work. On original hardware the range (lines) are visible. This point goes to MelonDS. But what's the problem here with DeSmuME? Do you have an idea?

**Comment by zeromus** [comment]
When reporting a bug TELL US WHAT GAME IT'S ON

**Comment by damil42** [comment]
@zeromus It's seems that you didn't read the issue text. It's Anno 1701. No reason to close immediately. lol

**Comment by zeromus** [comment]
For the record, this clown edited the post after I replied. 
This uses the "line" feature which is difficult to emulate.
Strangely the opengl renderer does a better job. Pick that instead of softrasterizer.

**Comment by damil42** [comment]
@zeromus Seriously, you insult me even this was your fault? Just check the GitHub history log in edited menu. And your post. I edited the post BEFORE your post! Not AFTER. The author can delete the content of the history, but not the entry and the timestamp. That means "for the record", it's proven that you're the "clown", not me. That's your words not mine. You should think before insulting strangers. What a toxic behavior... It's ridiculous... Do you understand, that this is your fault?

**Comment by zeromus** [comment]
Hm it seems I got an email notification for the original version but not for the updated version so what I was looking at was the original version. I'm sorry for calling you a clown, but you falsely accused me of not having read the issue text and then lectured me like dad about using an inside voice and then laughed in my face, and then continued to behave comically, so I'll call you a clown again (but I'll also agree I'm a clown too)

**Comment by zeromus** [comment]
It's not "disabled", it's just broken. Each renderer has its own bugs. Sometimes by design kind of and sometimes by freak emergent chance.
