### ISSUE TITLE
Dynamic Recompiler bug - Sims 2 graphics invisible

### ISSUE THREAD

**Issue by user18081972** [TASEmulators/desmume#644]
**My enviorment**:
Game: Sims 2 (NTR-ASJE-USA)
Versions tested:
DeSmuME 0.9.9a.
DeSmuME 0.9.13
DeSmuME 0.9.14 git#56251ca x64-JIT SSE2 (March 3 23)

**Issue**
With DynaRec 16 or above, essential sprites/graphics are invisible.
Both OpenGL 3.2 and SoftwareRasterizer are affected.
All mentioned versions of DeSmuME are affected
![image](https://user-images.githubusercontent.com/124319511/223142894-8053c6ad-d23c-4cf3-84cd-c0b4be9b4721.png)

**Steps to reproduce**
1. Delete desmume.ini
2. Set Dynamic Recompiler to 16 or above.
3. Boot game, look at main menu.

**Comment by zeromus** [comment]
Dynarec is a hack, bigger numbers are bigger hacks. Bugs solved by choosing numbers are by design.
