### ISSUE TITLE
[Feature Request] Choose how written save is formatted

### ISSUE THREAD

**Issue by aliclubb** [TASEmulators/desmume#647]
Greetings! It would be wonderful if we could choose how save files get written to disk. By this I mean, an option to write the save file without the |<--Snip above here blah blah blah text. I know we can import RAW save files already, but it would just allow easier transfers between DeSmuME and real hardware flash carts, as well as other emulators.

**Comment by zeromus** [comment]
If desmume didn't need the footer, it wouldn't create it. I have no idea how any other emulator figures out how big the save data is. In general it can't be found out until the game saves, and in some rare cases it can't be found out until later than that. The footer tracks the state of that detection.
