### ISSUE TITLE
Desmume can't read saves if save type detection is set to from database

### ISSUE THREAD

**Issue by kotenok2000** [TASEmulators/desmume#648]
I have imported ADVANsCEne_RToolDS.xml from https://github.com/SiloDS/RToolDS/blob/master/src/ADVANsCEne_RToolDS.xml

**Comment by zeromus** [comment]
Works fine for me
1. boot robots
2. pick language
3. close emulator
4. open emulator
5. change save type detection to database
6. close emulator
7. open emulator
8. boot robots
9. observe language menu doesnt show: save data has been successfully loaded
