### ISSUE TITLE
ALU instructions with ROR #imm shifts on the second operand are not disassembled correctly

### ISSUE THREAD

**Issue by tertu-m** [TASEmulators/desmume#652]
An example instruction is `E041C2E2: sub r12, r1, r2, ror #5`. This is disassembled as `SUB R12, R1, R2, RRX`. I believe this is an issue with one of the macros used in the disassembler, but I am not exactly sure where the issue is. The issue occurred in DeSmuME 0.9.13 on Windows.

**Comment by zeromus** [comment]
I think it needed to be done in all of them... I could be wrong. But this does fix your case, at least. Try just a plain RRX and see if the results are still acceptable to you?
