### ISSUE TITLE
software renderer issue in 7751b59

### ISSUE THREAD

**Issue by windwakr** [TASEmulators/desmume#653]
While playing through Castlevania: Dawn of Sorrow recently I've noticed a bunch of instances of enemy body parts being rendered in the incorrect order. I've tracked this down to commit [7751b59](https://github.com/TASEmulators/desmume/commit/7751b5988280fd3f382110f4c5c06ebfd8513764). It only seems to affect the software renderer.

In the attached screenshot all 4 enemies should have their eyes closed, but the two on the right have the eyeball appearing on top of the eyelid.
![Untitled](https://user-images.githubusercontent.com/284886/232334590-82cdce03-145a-4887-ba84-0eb618869e65.png)

**Comment by rogerman** [comment]
Pretty sure that this problem is due to precision issues in Z-depth caused by my recent changes to integer-based calculations. (W-depth should still be fine.)

I'm taking a look at it.

**Comment by rogerman** [comment]
@windwakr, could you provide a .dsv battery file (or a .dst save state file), and also give me the ROM serial (which you can find under File > ROM Info) so that I can test this bug?

**Comment by rogerman** [comment]
@windwakr, try commit bf344e9.

**Comment by zeromus** [comment]
while youre working on softrasterizer issues, how about this?
http://forums.desmume.org/viewtopic.php?id=12307&p=2
I checked it myself and could find no problem. Seems so unlikely that it's truly mac only but.. i guess it's possible

**Comment by windwakr** [comment]
Sorry, I didn't see your other message. Seems to be fixed.

One of the things I checked was this boss and he still has problems with his elbow, but it might be a different bug. Seems to happen in builds before [7751b59](https://github.com/TASEmulators/desmume/commit/7751b5988280fd3f382110f4c5c06ebfd8513764) and also affects the OpenGL renderer. Doesn't happen on real hardware.
![Untitled](https://user-images.githubusercontent.com/284886/236331261-87d0df0e-3f58-4413-89c5-d1a4cad33250.png)
But here's a save file right before him if you want it.
[Castlevania - Dawn of Sorrow.zip](https://github.com/TASEmulators/desmume/files/11401634/Castlevania.-.Dawn.of.Sorrow.zip)

**Comment by rogerman** [comment]
@windwakr, thanks for confirming that the bug is fixed. I'll close out this issue and note that commit bf344e9 is what fixed it.

Concerning this boss battle elbow bug, please make a new ticket for it. I will need the ROM serial (or game code) from File > ROM Info, since Castlevania: DoS has multiple versions and I need to test the right one.
