### ISSUE TITLE
Import Backup Memory on Linux has no import options?

### ISSUE THREAD

**Issue by trymeouteh** [TASEmulators/desmume#654]
I installed the DeSmuME flatpak and imported my SAV saves into DeSmuME and I did not have to fiddle with the import settings. On Windows, when you import a SAV file using the File->Import Backup Memory feature, a window will appear on the import settings of the save with options such as...

```
AUTO (From Current Save Data Size)
AUTO (From ADVANsCEne Database)
Manual
```

Why is this not on Linux? So far the saves I have imported on Linux works. Or why then do we need to choose how SAV files are imported on Windows and not have it fully automated like on Linux?

**Comment by zeromus** [comment]
It's not on linux because there are fewer developers on linux and the feature was never added. Congratulations on your getting lucky with the auto importing succeeding.

**Comment by trymeouteh** [comment]
> Congratulations on your getting lucky with the auto importing succeeding.

Not all saves can be imported on the linux client but most or all saves can be imported on the windows client?

**Comment by zeromus** [comment]
That's right. Now if you're preparing to express shock, OUTRAGE at the lack of feature parity, don't bother.

**Comment by trymeouteh** [comment]
Can I open a feature request for this issue in hopes it will get added someday for Linux?

**Comment by zeromus** [comment]
Yes. It will then be closed and merged in here
https://github.com/TASEmulators/desmume/issues/209
