### ISSUE TITLE
[Feat Request] Import Backup Memory settings on Linux

### ISSUE THREAD

**Issue by trymeouteh** [TASEmulators/desmume#655]
Adding import options when importing SAV files into DeSmuME on Linux, just like there is for Windows.

https://github.com/TASEmulators/desmume/issues/654

**Comment by trymeouteh** [comment]
https://github.com/TASEmulators/desmume/issues/655

**Comment by trymeouteh** [comment]
https://github.com/TASEmulators/desmume/issues/209

**Comment by rofl0r** [comment]
fyi i added this feature to gtk+2 version, but not gtk+3, as i only use the former.

**Comment by rofl0r** [comment]
commit in question is b1ffe0ae7670ff0a6b5e9c86a18ba2b401b47617 , for some able to build gtk+3 version it should be straightforward to port it there.
