### ISSUE TITLE
WarioWare spazzing out 

### ISSUE THREAD

**Issue by dochoogbrain** [TASEmulators/desmume#656]
Whenever I drag my mouse on the WarioWare touched, it dies and drops to 1fps. I don't know what to do or how to fix it.

**Comment by zeromus** [comment]
uninstall "desktop enhancements" or "mouse drivers" or "touchpad drivers" or "cool streaming broadcast software" or "security suite" or anything else that seems like it makes your system super awesome, since it actually just breaks things.
