### ISSUE TITLE
fast forward does not work

### ISSUE THREAD

**Issue by Scooby1219** [TASEmulators/desmume#658]
i watched a tutorial on yt on how to set it up and ive been told to set it with the same hotkey as "fast forward toggle", i also tried using 2 different hotkeys but it still does not work (im using the latest version of desmume)
![image](https://user-images.githubusercontent.com/131589314/233835099-73acc638-a174-4b80-9ccb-4b3d32a4b13d.png)

**Comment by zeromus** [comment]
Binding the same key to both those functions makes no sense and is not supported.
