### ISSUE TITLE
LINUX CLI Input Sanitation Issue

### ISSUE THREAD

**Issue by LadyLandshark** [TASEmulators/desmume#663]
Found an input validation error as part of ForAllSecure's [MayhemHeroes](https://github.com/mayhemheroes) program. Fuzzing the Linux `desmume-cli` binary using the `micsamples` directory as a seed corpus revealed an input validation error. Attached is the backtrace and two crashing inputs. As part of Mayhem Heroes I will be submitting a CVE. 

[crashing_inputs.zip](https://github.com/TASEmulators/desmume/files/11465920/crashing_inputs.zip)

[desmume_defect_backtrace.txt](https://github.com/TASEmulators/desmume/files/11465893/desmume_defect_backtrace.txt)

**Comment by rofl0r** [comment]
care to provide a PR ? it would be more helpful than CVE circus.

**Comment by zeromus** [comment]
Will they still get credit for their homework without filing a cve? If I was a prof I would be more impressed with a PR for sure.

**Comment by LadyLandshark** [comment]
This is paid contract work. Here is the PR on the [mayhemheroes fork](https://github.com/mayhemheroes/desmume/pull/1). Unfortunately it's outside of my scope to develop my own fix but I will be available to confirm any fixes.

**Comment by zeromus** [comment]
OK, we're not going to be turned into an arm of ForAllSecure marketing dept
