### ISSUE TITLE
MAC- the game Sonic Chronicles- The Dark Brotherhood stops when its explaining POW moves

### ISSUE THREAD

**Issue by Samy112** [TASEmulators/desmume#664]
[ BEGIN DESMUME TROUBLESHOOTING INFORMATION ]

App Version:  0.9.13 x64 SSE4.2+AVX2 (LLVM-Clang v13.1.6)
Operating System: macOS v13.3.1 (22E261)
Model Identifier: iMac18,2
ROM Name: SONICCHRON
ROM Serial: NTR-CSNP-EUR

Emulation Speed: 1.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: None
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 9x
GPU - Color Depth: 15-bit
3D Renderer - Engine: OpenGL (MSAA=Off, SmoothTextures=NO)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Video - Output Engine: macOS Metal GPUFamily2_v1 (AMD Radeon Pro 555)
Audio - Output Engine: macOS Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method

Cheats: NO

Observed Behavior: The game stops exactly when is explaining the POW moves

Expected Behavior: The game should continue with no problems

[ END DESMUME TROUBLESHOOTING INFORMATION ]

**Comment by zeromus** [comment]
Bad dump probably. Ask google for 100s of pages of lore about this. Acquire a different rom.
