### ISSUE TITLE
stuck on are you a boy or girl

### ISSUE THREAD

**Issue by KasperWebink** [TASEmulators/desmume#665]
Im playing pokemon platinum randomized but i can't get further then are you a boy or a girl. It resets every time. any tips?

**Comment by zeromus** [comment]
haha! sounds like something you might need to take up with a counselor. 
Also. Actually.
Bummer! Sounds like something you need to take up with the vendor of the randomizer or its community. They're corrupting your rom. Broken rom resets. Not desmume's problem.
