### ISSUE TITLE
The ROM header is invalid. The device size has been increased to allow for the provided file size.

### ISSUE THREAD

**Issue by Lune24** [TASEmulators/desmume#668]
Hello, I had been playing the sims 2 ds for a few days and this message started to appear, it is impossible to start the game with the progress because every time I try to start it, this message appears. I don't know how to fix it. The rom works perfectly because I can start the game without the progress, the problem is that, the saves. I have each file in its place, in the battery folder, I have the .dsv progress in its folder too and the rom the same. I don't know what I may be doing wrong. I've read somewhere that when the save file reaches 1mb this message appears, but I don't know if it's true.

**Comment by zeromus** [comment]
Keep everything in one directory (that is, put rom in desmume directory; everything else is automatically created alongside desmume.exe) and then zip it. it's just files. It's all under your control.

**Comment by Lune24** [comment]
Okey thank you so much for your time <3

**Comment by zeromus** [comment]
Note, some programs (including some emulators) litter garbage all over your disk and finding it all is a challenge. So this technique won't work for every application. But it does work for desmume.

**Comment by Lune24** [comment]
It's good to know, I'll definitely come back if I have any other questions. Very good attention thank you
