### ISSUE TITLE
I hear nothing.

### ISSUE THREAD

**Issue by MIninjaYoshi** [TASEmulators/desmume#675]
One day, I downloaded the desmume to play pokemon. At first day, everything went fine, but after logging on the same save file... the music just stopped playing. I checked everything. I reset, deleted my file, tried on different game. Nothing worked. I viewed the sound state. It looks like music is there, I just cannot hear it. My headphones or music everywhere else are fine, but not here. Can someone tell me what can I try?

**Comment by zeromus** [comment]
one of these will fix it.
1. delete desmume.ini
2. ask someone how to use your computer. you muted the desmume process in the OS control panel on accident
