### ISSUE TITLE
Pokemon black

### ISSUE THREAD

**Issue by cookietakesover** [TASEmulators/desmume#676]
It wont let me open the menu to see my pokemon or items.

**Comment by zeromus** [comment]
You're pressing the wrong button. Who told you to press which button? Did you try pressing the other buttons?

**Comment by cookietakesover** [comment]
im pressing every button. ive configured the controls, still doesnt work

**Comment by zeromus** [comment]
I don't think you tried pressing the 'S' key on your keyboard which is the default binding for the 'X' button
