### ISSUE TITLE
Lua51.dll error

### ISSUE THREAD

**Issue by Malik177** [TASEmulators/desmume#677]
I'm using desmume version 0.9.13. win x64. I don't understand whats happening. The dll file I downloaded from dll-files.com didn't solve the problem. I made sure to download the 64 version since the application is x64. Even downloading the 
lua-5.1.5_Win32_dll14_lib.zip from the post zeromus made on sourceforge didn't work and I made to use this for an older version of desmume that is 32 bit aka x86

**Comment by zeromus** [comment]
https://github.com/TASEmulators/desmume/blob/master/desmume/src/frontend/windows/lua/lua.7z
dearchive x64 dlls to directory containing desmume.exe
