### ISSUE TITLE
Runs very slow only when the DeSmuME window is in foreground

### ISSUE THREAD

**Issue by JasonWei512** [TASEmulators/desmume#680]
This bug may sound strange.

On my Windows PC, when the DeSmuME window is in foreground, the emulation will run very slow (like 10 fps).
When I switch to another window and the DeSmuME window is in background, the emulation will run at full speed (60 fps).
My PC's specs:
```
CPU: AMD Ryzen 3700x
GPU: Nvidia 2070 Super
RAM: 32 GB
SSD: 2 TB
OS:  Windows 11 22H2 22623.1245
```

On my old laptop I don't see this bug.
My old laptop's specs:
```
CPU: Intel i5 7300 U
GPU: Intel HD 620
RAM: 8 GB
SSD: 256 GB
OS:  Windows 11 22H2 22623.1245
```

I am using DeSmuME `0.9.13`, downloaded from GitHub Release, using default emulation settings.

**Comment by JasonWei512** [comment]
This happens to nightly builds too.

**Comment by zeromus** [comment]
This is the fault of low quality GPU drivers. Upgrade or downgrade your GPU drivers, or change the GPU driver options regarding "mult-thread optimizations" or any kind of so-called "optimizations" at all.
change desmume's config > display method.
change your system power options to be less "smart" and more "dumb" (only something really "smart" can make such a dumb mistake as running the foreground window at 1fps)

**Comment by JasonWei512** [comment]
Thanks. Changing display mehotd to OpenGL solves the problem.

**Comment by zeromus** [comment]
You could file a bug report with intel if you want them to have something to not care at all about.
