### ISSUE TITLE
Website download points to older version

### ISSUE THREAD

**Issue by JH2535** [TASEmulators/desmume#682]
I went to download desmume from the website here https://www.desmume.com/download.htm and clicked on the windows 10 version which pointed me to https://sourceforge.net/projects/desmume/files/desmume/0.9.11/desmume-0.9.11-win64.zip/download which is the 0.9.11 version but looking at the releases the latest version (at the time of writing this) is 0.9.13. https://github.com/TASEmulators/desmume/releases

Can someone please update the download to point to the more recent version? Thanks

**Comment by zeromus** [comment]
we don't control desmume.com. address your complaints to the desmume.com webmaster.
