### ISSUE TITLE
Crash on quit when you click CLOSE window button

### ISSUE THREAD

**Issue by Hexaae** [TASEmulators/desmume#717]
0.9.14git#4e6a7f0 x64 JIT SSE2
Config (ini): https://paste.sh/89rai4Vb#BfKsBb47qf_EW2-qQRMJD_1Q  
Windows 11 22H2, NVidia drivers 536.67. ASUS GL703GS i7-8750H (6+6 cores), NVidia 1070 8GB (Max-p), 32GB RAM, 1920x1080 144Hz G-Sync laptop screen, Realtek HD Audio (ALC295 chipset), NVMe + SSD, Hori Fighting Stick Mini, XBox One BT controller, ROG Strix Carry mouse.

When I run any game, and while running I abruptly quit the emulator clicking on the CLOSE window gadget (upper-right red cross) it silently crashes on quit and Windows will log this kind of error every single time:

```
Descrizione
Percorso dell'applicazione che ha generato l'errore:	C:\Users\Luca\DeSmuME\DeSmuME.exe

Firma del problema
Nome evento problema:	APPCRASH
Nome applicazione:	DeSmuME.exe
Versione applicazione:	0.0.0.0
Timestamp applicazione:	64bee5f6
Nome modulo con errori:	StackHash_7a6d
Versione modulo con errori:	10.0.22621.1928
Timestamp modulo con errori:	7dd9e350
Codice eccezione:	c0000374
Offset eccezione:	PCH_4E_FROM_ntdll+0x000000000009F8A4
Versione SO:	10.0.22621.2.0.0.256.48
ID impostazioni locali:	1040
Informazioni aggiuntive 1:	7a6d
Ulteriori informazioni 2:	7a6de727f7647fad3039f1d59a3dc8b5
Ulteriori informazioni 3:	cf60
Ulteriori informazioni 4:	cf600af61ec319562540e2f1ccdf86b0
```

Won't crash using Quit from main menu.

**Comment by zeromus** [comment]
can't repro. probably a bug in "desktop enhancement", "hotkey managers", "gaming enhancers", "keyboard or mouse drivers" or gpu drivers. this kind of stuff happens when you have a junked up broken system. I haven't ever heard of this happening in desmume before. You may just have to clean your system or nuke it.

do changes to the ini file save before it crashes?

**Comment by Hexaae** [comment]
Sorry no, the system is perfect and is reproducible also on different PCs. This happens only for desmume of course in that special sequence explained in 1sst msg.

**Comment by zeromus** [comment]
happens only 1/10 times for me. depends on random factors, plus depends 100% on whether the game has played a non-looping sound to completion at the time you hit X. I don't think it has to do with whether you click the X or not, that's just another one of the random factors.

**Comment by Hexaae** [comment]
Can you kindly provide a binary ready to run?
