### ISSUE TITLE
Transfer saved data to nintendo ds possible, (.sav file)

### ISSUE THREAD

**Issue by bruno8290x** [TASEmulators/desmume#718]
I’ve bought recently a nintendo ds to play better the games that i’ve been playing on this emulator on my Iphone 12, I have had played a lot to these games, (Pokémon more specifically), naturally i want to have my saved data onto my m3 rom cartridge, is there any way that the saved data could be added into another folder in the dropbox option? Thanks

**Comment by zeromus** [comment]
we don't make the iphone desmume emulator. you're in the wrong place. you'll have to find whoever actually makes that.
