### ISSUE TITLE
Game is displayed sideways on 007 - Quantum of Solace (USA) (En,Fr) on DeSmuME 0.9.14 git#3955480 x64-JIT SSE2

### ISSUE THREAD

**Issue by kotenok2000** [TASEmulators/desmume#722]
![image](https://github.com/TASEmulators/desmume/assets/8822292/f5dbf7cf-e2bf-4b1b-b152-beab1f966ba5)
[desmume.ini.txt](https://github.com/TASEmulators/desmume/files/12345441/desmume.ini.txt)

![image](https://github.com/TASEmulators/desmume/assets/8822292/c53e64e2-0e33-43a9-b265-a38ff97c7944)
Other game titles display output correctly
![image](https://github.com/TASEmulators/desmume/assets/8822292/8e0218da-b0da-47e3-abd1-e5f79e96a592)

**Comment by zeromus** [comment]
view > rotation

**Comment by kotenok2000** [comment]
Your "fix" breaks games that were working before
![image](https://github.com/TASEmulators/desmume/assets/8822292/fa55bf58-82c9-4a7c-a7cb-840d1e7dc021)

**Comment by zeromus** [comment]
fix quantum of solace with config > display method. your operating system has a poor implementation of directdraw, which is the default. 

fix star fox with view > rotate. this is the intended design.

**Comment by rogerman** [comment]
Absolute user error going on here.

![quantum_solace_real_hardware](https://github.com/TASEmulators/desmume/assets/6055122/6db6783e-e505-4a4b-8c06-3b9d397278fd)

While most NDS games are designed with the typical top/bottom screen format, 007 Quantum Solace is one of several NDS games that is played by physically rotating the NDS itself, described by Nintendo as playing in "book" format. DeSmuME's rotation controls are provided to account for book format, allowing the user to virtually rotate their emulated NDS. There is no error going on here -- DeSmuME is displaying 007 Quantum Solace exactly as it was designed.
