### ISSUE TITLE
Build failure on Fedora

### ISSUE THREAD

**Issue by alexfornuto** [TASEmulators/desmume#729]
Hi friends. Not sure why I can't build this. The output is long and I'm not sure what's relevant, so [here's a pastebin](https://pastebin.com/9QYedCm7).

I believe I have all the correct dependencies:

```c
❯ meson setup --reconfigure --buildtype=release ./build
The Meson build system
Version: 1.0.1
Source dir: /home/alex/Downloads/desmume-0.9.13/desmume/src/frontend/posix
Build dir: /home/alex/Downloads/desmume-0.9.13/desmume/src/frontend/posix/build
Build type: native build
Project name: desmume
Project version: 2.7.10
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)")
C linker for the host machine: cc ld.bfd 2.39-9
C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)")
C++ linker for the host machine: c++ ld.bfd 2.39-9
Host machine cpu family: x86_64
Host machine cpu: x86_64
Dependency glib-2.0 found: YES 2.76.5 (cached)
Dependency sdl2 found: YES 2.26.3 (cached)
Dependency pcap found: YES 1.10.3 (cached)
Dependency zlib found: YES 1.2.13 (cached)
Dependency threads found: YES unknown (cached)
Dependency gl found: YES 1.2 (cached)
Dependency openal found: YES 1.23.0 (cached)
Dependency alsa found: YES 1.2.10 (cached)
Dependency soundtouch found: YES 2.3.1 (cached)
Dependency libagg found: YES 2.5.0 (cached)
meson.build:227: WARNING: Module SIMD has no backwards or forwards compatibility and might not exist in future releases.
Compiler supports sse2: YES
Dependency x11 found: YES 1.8.6 (cached)
Dependency gtk+-3.0 found: YES 3.24.38 (cached)
Dependency x11 found: YES 1.8.6 (cached)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Build targets in project: 6

desmume 2.7.10

  User defined options
    buildtype: release

Found ninja-1.11.1 at /usr/bin/ninja
```

Attempting on Fedora 38, happy to provide any additional information that could help troubleshoot.

**Comment by zeromus** [comment]
type "const" in the beginning of line 1378 of agg_renderer_outline_aa.h

`const line_profile_aa& profile() { return *m_profile; }`

**Comment by alexfornuto** [comment]
The only instance of that line/file I found was in `/src/frontend/windows/aff/include`. I wouldn't think that the windows dir would affect the build in Linux, but what do I know?

After editing and running again: [output](https://pastebin.com/jtb9fB2Z)

**Comment by zeromus** [comment]
The path to the file is listed in your output. Ctrl+f for it

**Comment by alexfornuto** [comment]
Ahh, I see. Thank you.

**Comment by zeromus** [comment]
you should report it to whoever is maintaining antigrain geometry library now. it's kind of a dead library but there has to be some linux maintainer doing little fixes like this

**Comment by alexfornuto** [comment]
@zeromus I would, if I knew enough to make a half-decent bug report. You already know more about the problem than I do.

**Comment by zeromus** [comment]
I don't know how to send bug reports to linux package maintainers. I don't use linux. 
1. See if even a simple cpp file that does nothing but include the AGG top level header compiles on your system
2. if it works, then begin stripping down deposterize.cpp to a minimal test case. it could be something sneaky provoking a compiler problem, but most likely step 1 will have failed

you could also try googling for this error because people DO use agg, even if it's abandoned. if compilers stopped supporting it, bugs will crop up

**Comment by alexfornuto** [comment]
I found the repo and submitted a PR to add the `const` declaration. Seems more direct than a bug report.

The steps you suggested probably sound trivial to you. I'm not a dev. I use the cool shit that devs make, and sometimes I even write the docs for them so others can also use it.

It's good to keep in mind that the users of your software likely don't have the same knowledge you do.

**Comment by zeromus** [comment]
I'm well aware. I'm trying to encourage people learn. If I get lectures on manners from people who don't want to learn this exact thing this exact moment then that's fine. I'm not optimizing for the case of you.
