### ISSUE TITLE
I have a problem with the microphone

### ISSUE THREAD

**Issue by ayudanopuedosoplar** [TASEmulators/desmume#734]
My NDS emulator (Desmume) don't have a microphone and im stuck in a part of the game where i need to blow air, the worst part is i can't restart

**Comment by zeromus** [comment]
Are you telling me you can't find anything about this on the internet? Find mic samples and hold the microphone hotkey.

http://wiki.desmume.org/index.php?title=Faq
Can DeSmuME emulate the DS microphone?
