### ISSUE TITLE
I am having trouble loading my battery save

### ISSUE THREAD

**Issue by hollev1** [TASEmulators/desmume#740]
I am playing Pokemon platinum and I have just transferred my battery save from the original game to the NTEVO version. When I open up the NTEVO version everything seems fine. I can see the save and everything but when I press continue it seems like it's just loading infinitely. So my game is just stuck in a loading state. Like this:
![D2CCA765-8919-4C5B-B119-D1167BC049A1](https://github.com/TASEmulators/desmume/assets/148084492/748871e0-1f6c-414f-bb93-4432fa127be7)

Help would be greatly appreciated.

**Comment by rofl0r** [comment]
> NTEVO version

is that some sort of romhack ?

**Comment by hollev1** [comment]
Yes, I think so at least. The guy who made it said that it would be fully compatible with a battery save from the main game.

**Comment by zeromus** [comment]
did you patch the exact rom you played on originally? or did you download a prepatched NTEVO rom.. perhaps... based on a different region than the one you played on originally?

**Comment by hollev1** [comment]
> did you patch the exact rom you played on originally? or did you download a prepatched NTEVO rom.. perhaps... based on a different region than the one you played on originally?

What do you mean by patch the exact ROM. I'm new to this emulator stuff so, I don't know. The reason for me trying to get my save to load on the NTEVO ROM is because I would like to make impossible evolutions possible. Is there any other way to bypass this issue?

**Comment by zeromus** [comment]
I guess you answered your question yourself? Using hacks and transferring save data is not a good activity for emulation newbies. You need to find gaming friends. But maybe youve learned enough now to not be a newbie anymore
