### ISSUE TITLE
Little thing: update the links to HTTPS 🙂

### ISSUE THREAD

**Issue by PrSunflower** [TASEmulators/desmume#741]
Hello dear community 👋

Just a little request: on GitHub (and maybe in other places) your URL links point to the **unencrypted** : http://desmume.org/

Possible to update your links to the **HTTPS website**? https://desmume.org/ (it loads just as fast)

Keep up the good work! Cheers! ✌️

<br>

_P.S. :_ If you want to do even better, you could configure your HTTP server to always redirect to the HTTPS website. 🤭

**Comment by zeromus** [comment]
no thanks.
