### ISSUE TITLE
Can't open desmume

### ISSUE THREAD

**Issue by Seikooooooo** [TASEmulators/desmume#743]
hi i got a new pc and i try install this amazing emulator but i got an issues and i don't how to fix it, i have a system error telling me the code MSVCP140.dll not found and try reinstall the program. ofc i did that multiple times but nothing, idk what to do pls help me i want to win over cinthia in pokemon black ,this is driving me crazy

**Comment by Jules-A** [comment]
There's a entry for this in the Desmume FAQ: http://wiki.desmume.org/index.php?title=Faq#vcruntime140_1.dll_was_not_found though technically it's a different file I'm pretty sure it's the same issue.

Install the latest x86/x64 c++ redistributables for 2015/2017/2019/2022 from here: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Seikooooooo** [comment]
thanks bro 
all fix now
