### ISSUE TITLE
Crash when moving Scolipede

### ISSUE THREAD

**Issue by Iccy03** [TASEmulators/desmume#745]
Whenever I try to put my shiny scolipede back into my party from my pc, the game freezes. I did catch said shiny scolipede with the shiny cheat, but i tried moving around other shinies that I got the same way and nothing went wrong

**Comment by Iccy03** [comment]
(Pokemon White 2)

**Comment by Iccy03** [comment]
scratch that, its any shiny pokemon that I got using the cheat. Moving from box to party causes the freeze

**Comment by zeromus** [comment]
so in a nutshell: you cheated and the game broke?
