### ISSUE TITLE
Inazuma Eleven savefile got deleted

### ISSUE THREAD

**Issue by luk128Gh** [TASEmulators/desmume#746]
pretty self explanatory, i played the whole story and leave the postgame for later, a few weeks pass, and when i open the game, my savefile is gone and only the new game option is avaible, this happened before, but i had less than 1 hour in so i didnt give it much importance but now...yeah, any fixes?

**Comment by zeromus** [comment]
don't run desmume from the zipfile directly. dearchive it to a directory on your desktop.

**Comment by luk128Gh** [comment]
Yeah, that's done, I've always opened it like you say, but the save file is gone for no reason

**Comment by zeromus** [comment]
Then your kid brother messed around with your computer, or your hard drive is getting corrupted. Desmume save files don't just disappear.
