### ISSUE TITLE
Desume not loading game, stuck on black screen.

### ISSUE THREAD

**Issue by romillypom** [TASEmulators/desmume#747]
[ BEGIN DESMUME TROUBLESHOOTING INFORMATION ]

App Version:  0.9.13 ARM64 NEON-A64 (LLVM-Clang v13.1.6)
Operating System: macOS v13.3.1 (22E261)
Model Identifier: MacBookPro18,3
ROM Name: Unspecified
ROM Serial: Unspecified

Emulation Speed: 1.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Uninitialized
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 18-bit
3D Renderer - Engine: None (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Video - Output Engine: macOS Metal GPUFamily2_v1 (Apple M1 Pro)
Audio - Output Engine: macOS Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method

Cheats: NO

Observed Behavior: I observed the game freeze. When restarting the ROM, I observed a black screen. 

Expected Behavior: I expected the game to open as normal. 

[ END DESMUME TROUBLESHOOTING INFORMATION ]

**Comment by rogerman** [comment]
You haven't provided any information about which game is freezing and/or presenting a black screen. You need to run the game first, then in the Bug Report window, click Use Currently Loaded ROM to fill in the ROM Name and ROM Serial information. This is critical information for debugging.

Looking to close this ticket if the ROM Name and ROM Serial information aren't provided.

**Comment by zeromus** [comment]
Also try more than one rom...

**Comment by rogerman** [comment]
This ticket remains non-sensical and the user has failed to clarify after two weeks.

Closing.
