### ISSUE TITLE
yikes!!!!! please report!

### ISSUE THREAD

**Issue by kellda** [TASEmulators/desmume#749]
This displayed in my console (using DeSmuME 0.9.11 svn0 dev+ x64-JIT). What would you like me to report ? cc @zeromus

**Comment by zeromus** [comment]
what you were doing when it happened, perhaps?

**Comment by kellda** [comment]
I was playing/testing a simple game with desmume, which used the sound and the touchscreen (not sure whether it's related). The message appeared anytime and as long as I clicked/had the pen down on the simulator's "touchscreen".

Do you need any other information, source code or compiled files ?

**Comment by zeromus** [comment]
So you're running a homebrew that abuses the timers. Maybe you set one to the maximum possible frequency. At this point I don't have time to debug a malfunctioning homebrew. It's not helping smoke out an emulation error. There's an "optimization" that hopes the timers don't run too fast. As long as it's not striking normal games, that's as good as it's going to get.

**Comment by zeromus** [comment]
useless bug with no rom
