### ISSUE TITLE
Can't install for Mac

### ISSUE THREAD

**Issue by philina1999** [TASEmulators/desmume#750]
When I try to install desmume my Mac says that it can't be installed, because Apple can't look for malware. Pls fix I wanna install it.

**Comment by rogerman** [comment]
There is no installation. Simply copy DeSmuME.app from the .dmg to your favorite location and run that.

When running DeSmuME.app for the first time, you'll need to follow these instructions:
http://wiki.desmume.org/index.php?title=Faq#I_just_downloaded_DeSmuME.2C_but_I_can.27t_launch_it_because_.22it_is_from_an_unidentified_developer..22_What_gives.3F
