### ISSUE TITLE
Can't open File Explorer

### ISSUE THREAD

**Issue by RandomSteve42** [TASEmulators/desmume#754]
Desmume runs all my roms but for some reason when I open file explorer to add a new program it will not respond and I have to close Desmume.

**Comment by zeromus** [comment]
You mean when you use windows explorer to set the file association for .nds and then doubleclick an NDS, desmume freezes? Sounds like you're running desmume from a strange directory like program files or c:\ instead of your user directory or desktop

**Comment by RandomSteve42** [comment]
I run Desmume from my desktop. When I boot it up if I click open roms it fails to load my files. More so it fails to pull them up cause it will run my roms that I have in recent roms.

**Comment by zeromus** [comment]
it fails to load your files, or it "will not respond"? which is it?

**Comment by RandomSteve42** [comment]
It fails to respond sorry for not clarifying originally.

**Comment by zeromus** [comment]
if you boot desmume, then you didn't double click the .nds but rather ran the EXE completely. 

Suppose you think you're explaining the situation with 10 our of 10 clarity units. Imagine what 1 clarity unit might be, or 5. Now let me tell you: you're explaining the situation actually with 2 clarity units. There are 8 more clarity units to find somewhere. Look for them. And write clearly what you are doing, with more than the absolute minimum effort. I have typed more words asking you about your lazy minimum effort complaints than you've typed in complaints.

**Comment by RandomSteve42** [comment]
OK so I double click demume on my desktop I have version 9.13. From there I click open roms this pops up the files in its own tab at which point it says "working on it." Once this happens it just sits there till eventually it says not responding I will post a picture below. 

![image](https://github.com/TASEmulators/desmume/assets/131079776/28da159f-4ca7-4806-b1f7-950c8b6ca05a)

**Comment by RandomSteve42** [comment]
That is what I click before it stops responding.

**Comment by zeromus** [comment]
this is not a problem with desmume. it is a problem from junkware you've installed. search for junk/spy/crapware, especially anything that claims to "enhance" anything, especially explorer or context menus) and uninstall it. It could also be caused by glitching external drives, glitching internal drives, or almost anything else.

**Comment by Jules-A** [comment]
Maybe an issue with c++ redistributes. Uninstall any 2015-2022 Microsoft Visual C++ Redistributables and install the latest version from: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

If it still doesn't work, maybe try deleting desmume,ini, running as administrator, opening files from a location that doesn't require admin, adding desmume to anti-virus exceptions (if you are using something other than Windows Defender).
