### ISSUE TITLE
controller issue

### ISSUE THREAD

**Issue by sulfur-deposite** [TASEmulators/desmume#756]
I've tried my best but it wont allow me to use a secondary control input option, I've tried many controllers- please help

**Comment by zeromus** [comment]
What's a "secondary control input option"? Do you mean you want two keys to control the same NDS button? It's impossible in the windows port of desmume. You didn't say what OS you're running, so I'll just assume.

**Comment by sulfur-deposite** [comment]
a secondary input is a controler or keyboard connected to your computer- but the issue is that desmume wont let me map controls on a controller

**Comment by zeromus** [comment]
works for me every time. you need a directinput compatible gamepad though.

**Comment by sulfur-deposite** [comment]
is their a software i need to download, this hasn't helped me any

**Comment by sulfur-deposite** [comment]
so i figured that issue out, had to run the program as administrator- weird
but now i have a new question, is it possible to map the touchscreen directions to a controller?
