### ISSUE TITLE
cant add pokemon into my party

### ISSUE THREAD

**Issue by RealCLaytonFC** [TASEmulators/desmume#758]
playing pokemon white 2 and got all the way to victory road but now everytime i try to put a mon from my pc into my party the game crashes.

**Comment by zeromus** [comment]
stop using savestates. save in-game frequently, close the emulator, open it again, and load the in-game save. stop using old desmume versions. stop using desmume or pokemon hacks or cracks. don't expect wifi features to work: wifi is not supported. etc.
