### ISSUE TITLE
[Question] Linux: is "GPU scaling factor" supported?

### ISSUE THREAD

**Issue by thesourcehim** [TASEmulators/desmume#763]
Is this feature supported under linux? No such option in GTK3 frontend.

**Comment by rofl0r** [comment]
it's supported in the posix cli version, for which i implemented it. feel free to add support to it to GTK3 version, which i couldn't as meson doesn't run on my system.

**Comment by thesourcehim** [comment]
Err, I guess I'm being dumb here, but could you please point me where it's implemented in cli, I can't find it. Is it in your forked repo?

**Comment by rofl0r** [comment]
90326ea1f9c9b4396b9b5e82f78112c4e8e9ce6d
