### ISSUE TITLE
Sonic Rush Adventure intro slowdown and desync

### ISSUE THREAD

**Issue by DarthPidgey** [TASEmulators/desmume#774]
The intro to Sonic Rush Adventure slows down when Tails and Marine and the Dolphins show leading to the audio of the cutscene getting desynced and having silence before the cutscene finishes. Funnily enough this same thing happens on real hardware if you play the game on a flashcart. But on real hardware and a real authentic cart there's no slowdown or silence.

**Comment by zeromus** [comment]
disable advanced bus-level timing
