### ISSUE TITLE
Kirby Super Star Ultra screen transition full white fade not working

### ISSUE THREAD

**Issue by DarthPidgey** [TASEmulators/desmume#775]
When there's a screen transition in this game there is flashes of white or green that's not there on real hardware

**Comment by zeromus** [comment]
this is caused by dispcnt ForceBlank not being implemented. When set, the screens should both be 100% white
I could do this (it's not very hard), but I'm 100% rogerman will hate however i do it.
We'll give @rogerman a chance to do it
