### ISSUE TITLE
Problem when fullscreen, background full white and a stuck image on the left, how to resolve ?

### ISSUE THREAD

**Issue by Sosozeus** [TASEmulators/desmume#777]
When I launch the game it is automaticaly on a smaller screen and when i put it on fullscreen the background is white and there is an image of the game when I had put it on fullscreen on the left, how can i resolve this so i can have a background full black ?
![reddit](https://github.com/TASEmulators/desmume/assets/162647191/b74929c0-af03-475e-8c10-16bb7509c505)

**Comment by rofl0r** [comment]
which port are you using ? windows, mac, linux, gtk2, gtk3... ?

**Comment by Sosozeus** [comment]
Im using windows 10

**Comment by zeromus** [comment]
change config > display method
