### ISSUE TITLE
It won't let me save any game

### ISSUE THREAD

**Issue by yasmin2834823482** [TASEmulators/desmume#778]
![Uploading imagen_2024-03-16_002412535.png…]()
I've been using this emulator for a few days and every time I tried to save the game it didn't let me and gave me an error :(

**Comment by zeromus** [comment]
"gave me an error"
(doesn't post the error)

**Comment by yasmin2834823482** [comment]
> "gave me an error" (doesn't post the error)

i post it i don't know why can't see it

**Comment by zeromus** [comment]
because you hit stray keystrokes. 
"didn't work"
(doesn't try again)
