### ISSUE TITLE
Lua51.dll

### ISSUE THREAD

**Issue by Ya-Block** [TASEmulators/desmume#779]
when i try to run a lua, it says
![image](https://github.com/TASEmulators/desmume/assets/146646463/3c60204c-98c8-40a1-9683-4a5abd7882e9)
even after adding the dll, it still shows the messege

**Comment by zeromus** [comment]
https://github.com/TASEmulators/desmume/issues/456

**Comment by Ya-Block** [comment]
dosent work

**Comment by zeromus** [comment]
Then you have a broken lua dll in your system path. scour them from WINDOWS and SYSTEM32 and etc.
