### ISSUE TITLE
stuck in speed up and clock/time issue

### ISSUE THREAD

**Issue by HawaiiCut** [TASEmulators/desmume#781]
Hey! im new to this emulator thing so go easy on me lol

first issue - my game is always sped up everytime i launch the emulator, i have no idea why? i have to delete the app everytime to fix it and its just annoying to fix all the settings again

second issue - i mainly play pokemon and im sure many of you know you can only catch certain pokemon at certain times a day. so i googled how to set the time in the emulator. (have start recording a movie and such..) and ive deleted the app but the time still wouldnt reset to the time on my system. its always set to 00:00 now.

would very much appreciate any help, thanks!
(english is not my native language, sorry)

**Comment by zeromus** [comment]
Tell me the URL of the desmume you downloaded.

**Comment by HawaiiCut** [comment]
> Tell me the URL of the desmume you downloaded.

https://github.com/TASEmulators/desmume/releases/tag/release_0_9_13 
i downloaded the win64.zip version of it if thats what tou mean

**Comment by zeromus** [comment]
first issue - since you have changed an option that affects desmume speed but don't know where it is, delete desmume.ini to reset all the options. You say you have "deleted the app" but you haven't or else you would have deleted the settings. Maybe you don't know what it means to "delete the app". 

second issue - stop using savestates. save in-game and close the emulator. open it again. load the rom. load your save data.

**Comment by HawaiiCut** [comment]
yeah thats what i mean, i wanna use speed up but it gets stuck in speed up. i delete everything and the settings get reset. then its fine until i close the emulator and and launch it again

**Comment by zeromus** [comment]
So you're telling me you know how to speed up the emulator, but not slow it down? What a weird problem to have. Here, you can solve the problem yourself by filling out this questionnaire:
1.  Please write what you did to speed it up: __________________
2. Now, please do that again to slow it down

**Comment by HawaiiCut** [comment]
wow thanks i didnt know i was replying to a retard, if someone else is interested in helping whos not a mongoloid feel free to comment.

**Comment by zeromus** [comment]
So are you going to fill in the blank or not?
