### ISSUE TITLE
Controller input not working properly

### ISSUE THREAD

**Issue by Schwertsascha51** [TASEmulators/desmume#783]
so i installed the new version and now it thinks my controller inputs are Keyboard inputs (for example: b is space)

**Comment by Schwertsascha51** [comment]
https://www.desmume.com/download.htm
0.9.13

**Comment by zeromus** [comment]
are you using a QWERTY keyboard layout

**Comment by Schwertsascha51** [comment]
no QWERTZ

**Comment by zeromus** [comment]
config > control config
rebind as you please

**Comment by Schwertsascha51** [comment]
the problem is that i want to play on a controller and when i press the r button it does nothing and the l button is apparently controll so i cant use that one either

**Comment by zeromus** [comment]
You're telling me if you get desmume 0.9.11 right now you can bind controls perfectly well, but you can't in desmume 0.9.13?

**Comment by Schwertsascha51** [comment]
i just tried 0.9.11 it doesnt work either

**Comment by thesourcehim** [comment]
> the problem is that i want to play on a controller and when i press the r button it does nothing and the l button is apparently controll so i cant use that one either

Please explain, what do you mean by 'L button is control'. Are you mapping your gamepad to keyboard by some software?
Also, do you plug you controller before or after desmume start? Desmume does not support hotplug.

**Comment by Schwertsascha51** [comment]
when i press the L button it says i pressed control. no i am not maping my controller to my keyboard 
before

**Comment by zeromus** [comment]
What gamepad are you using? Are you using a 3rd party program or driver to make it work?

**Comment by zeromus** [comment]
So you have never, ever used desmume with a switch pro controller before April 9?
Run joy.cpl and see if it's sending glitched input to your computer.

**Comment by Schwertsascha51** [comment]
no but i figured out the problem steam was running in the background and the desktop layout for controller input wasn't set to gamepad. i didn't even know that setting exsisted.

**Comment by Schwertsascha51** [comment]
no but i figured out the problem steam was running in the background and the desktop layout for controller input wasn't set to gamepad. i didn't even know that setting exsisted.

**Comment by zeromus** [comment]
I don't know what "desktop layout for controller input" means or for it to be set to gamepad, but steam counts as "3rd party program" if it's interfering with your gamepad input. I guess I'll have to start suggesting people quit steam to see if that helps.
