### ISSUE TITLE
got this

### ISSUE THREAD

**Issue by sergioelcool12319** [TASEmulators/desmume#785]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.

![Uploading DeSmuME 0.9.13 x64 SSE2 _ Rhythm Heaven_ Touchless 20-04-2024 13_09_58.png…]()

**Comment by zeromus** [comment]
issue is broken

**Comment by sergioelcool12319** [comment]
oh
