### ISSUE TITLE
Encountering save problem

### ISSUE THREAD

**Issue by ev0tto** [TASEmulators/desmume#786]
## State your operating system:
Windows 11

## DesMuME version
0.9.13 x64 SSE2

## Issue

I was playing Pokemon Mystery Dungeon Explorers Of Sky [NTR-P-C2SJ] when I attempted to save my game, but the save failed. Is this a feature, or is it an issue?

<details><summary>video</summary>

![](https://small.fileditchstuff.me/s10/GtXuBPYiAvntrgmgqOJm.mp4)

</details><br/>
if you can not watch video, here is a backup.

https://krakenfiles.com/view/CAxtUNoZhG/file.html

**Comment by ev0tto** [comment]
I believe I've found a solution. 
It was necessary to create a save file on the actual device first. As of now, save function are working correctly:)

**Comment by zeromus** [comment]
Works for me, on the first save. How far do I have to go until I can get it to save again?

**Comment by zeromus** [comment]
OK, I died in a dungeon and came back out and saved again with no problem. The solution to your problem of "couldnt save purely using desmume", is: "don't do whatever you did that's strange" such as for instance hack the rom, fool around with manually renaming or transplanting files, etc.
