### ISSUE TITLE
I Lost all my progress after I saved!!

### ISSUE THREAD

**Issue by Lilwoopwoop** [TASEmulators/desmume#787]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
e.g. 0.9.13 or git master

## Issue
When I was playing in the afternoon, I decided I wanted to play a different Pokemon game called Pokemon Infinite fusion. So I saved my pokemon heartgold and Pokemon Platinum on the emulator and the rom hack. after I downloaded it I went back to DesMuMe and all of my progress was GONE. I kept looking in my files, and i downloaded DesMuMe a thousand time. Now I am just crying since I don't have my saved state. Now I don't want to use DesMuMe and If I don't get my progress back I am not going to play it. So if you don't help me thats fine but all I am saying is that If your going to be an emulator atleast have a saved point. Also if I could get one back it would be the pokemon platinum.
(I was playing on version 9.13)

**Comment by zeromus** [comment]
Stop running desmume directly from the zipfile. Dearchive all files to a folder on your desktop.
