### ISSUE TITLE
white screen still occurring after turning service worker off 

### ISSUE THREAD

**Issue by fawnyeo** [TASEmulators/desmume#789]
using ds.44670 on ios, iphone 12 with latest ios update. turned off service worker for safari and still getting a white screen. 

i hav reinstalled the rom and re-added DS.44670 multiple times
![IMG_7760](https://github.com/TASEmulators/desmume/assets/102406279/fb8c9476-8b02-41f4-851e-2e0fa34d5dc6)

**Comment by zeromus** [comment]
We don't make the desmume version for IOS. You're in the wrong place.
