### ISSUE TITLE
DeSmuME keeps creating a file named "Pok魯n" on my desktop and storing all savefiles there

### ISSUE THREAD

**Issue by Camomillia** [TASEmulators/desmume#791]
## State your operating system:
Windows

## DesMuME version
0.9.13 x64 SSE2

## Issue
I can't find a way to change where it defaults to saving files, and it keeps recreating said folder everytime i boot it up. I don't understand why the random kanji and i couldn't find anything regarding it online, so i'm assuming this is not intended.

**Comment by zeromus** [comment]
it's creating Pok魯n.dsv because you're opening Pok魯n.nds
Delete desmume.ini and desmume will forget everything it knows.
Run desmume.exe from a directory under your control and the files will be created there instead of some other crazy place out of your control

**Comment by Camomillia** [comment]
I'm not opening Pok魯n.nds, i never even had any file with a kanji on my pc. the file i'm opening is called pokemonjusticesilver.nds. For the sake of testing, i deleted both the "Pok魯n" folder and the .ini file you mentioned and reopened desmume, and it still created a folder named "Pok魯n" on my desktop.

**Comment by Camomillia** [comment]
> it's creating Pok魯n.dsv because you're opening Pok魯n.nds Delete desmume.ini and desmume will forget everything it knows. Run desmume.exe from a directory under your control and the files will be created there instead of some other crazy place out of your control

I'm not opening Pok魯n.nds, i never even had any file with a kanji on my pc. the file i'm opening is called pokemonjusticesilver.nds. For the sake of testing, i deleted both the "Pok魯n" folder and the .ini file you mentioned and reopened desmume, and it still created a folder named "Pok魯n" on my desktop.

**Comment by zeromus** [comment]
That desmume.ini is impossible. After you open desmume with an ini file that looks like that and then close it, the ini file shall contain more things. It's likely there's another desmume.ini file in a location you're unaware of, and a desmume.exe you're unaware of is using it. Get control of your files.

**Comment by Camomillia** [comment]
i just reopened and indeed there are more things!
Window Rotate=0
Filter=0
Width=256
Height=384
Window Size=0
[Display]
FrameCounter=0
ScreenGap=0
[RamWatch]
SaveWindowPos=0
RWWindowPosX=0
RWWindowPosY=0
Auto-load=0
[Watches]
Recent Watch 1=
Recent Watch 2=
Recent Watch 3=
Recent Watch 4=
Recent Watch 5=
[Scripting]
Recent Lua Script 1=
Recent Lua Script 2=
Recent Lua Script 3=
Recent Lua Script 4=
Recent Lua Script 5=
Recent Lua Script 6=
Recent Lua Script 7=
Recent Lua Script 8=
Recent Lua Script 9=
Recent Lua Script 10=
Recent Lua Script 11=
Recent Lua Script 12=
Recent Lua Script 13=
Recent Lua Script 14=
Recent Lua Script 15=
[Sound]
Volume=100
idk what i'm doing wrong, i'm sorry (i'm not sure i understand what it means to "get control of my files")

**Comment by zeromus** [comment]
"get control of your files" means to eradicate every desmume-related files from your system other than the ones you're actually meaning to run. You have other junk littered about.

Whatever desmume.exe you opened which modified that ini file is in a clean configuration now. It will create files on your desktop only if itself is on your desktop (why would you do that?). Moreover it won't pull a kanji out of thin air.

Instead of putting desmume.exe on your desktop, put it IN A FOLDER ON YOUR DESKTOP. Then it will create files alongside itself IN THAT FOLDER instead of spilling onto your open desktop

**Comment by Camomillia** [comment]
desmume wasn't ever in my desktop!! its current location is: C:\Users\User\Desktop\Pokémon\Emulators\DeSmuME

but it doesnt create files there. i searched through my whole pc and found nothing related to either desmume or the mysterious Pok魯n thing. i'll try deleting everything and redownloading it.

**Comment by Camomillia** [comment]
i redownloaded it and opened it fresh, and it still had the same issue of creating the Pok魯n folder. it occurred to me that it might be due to the diacritical mark (it was the only thing i could think of) so i tried renaming the folder to Pokemon w/o the mark and this fixed it. Doesn't this qualify as a bug? It shouldn't freak out over a diacritical mark on the folder name.

**Comment by zeromus** [comment]
Oh, huh, I guess you're right

**Comment by zeromus** [comment]
Well, it's fixed now, but the workaround of not using letters with bits of lint stuck to them will help you for now
