### ISSUE TITLE
rom emelator

### ISSUE THREAD

**Issue by Rbel21s** [TASEmulators/desmume#794]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.

Hello,

I wanted to try Pokemon White 2 redux, But if want to make the file with the xdelta and try to patch it, it constantly say it doesnt work. And if I start the game on the emulator I cant start the game unfortunately....

**Comment by zeromus** [comment]
This isn't the support center for xdelta or pokemon reduxes

**Comment by Rbel21s** [comment]
where can I? its just an rom which doenst work

**Comment by zeromus** [comment]
I don't know. It's a hacked rom. Get help from rom hackers.
