### ISSUE TITLE
DeSmuME does not recognize wireless bluetooth controller.

### ISSUE THREAD

**Issue by baccinrafael** [TASEmulators/desmume#796]
## State your operating system:
Windows

## DesMuME version
0.9.13

## Issue
The emulator does not recognize bluetooth controller, only if its connected via usb (which is broken on my laptop). I have seen many other people with the same problem and no solution.

**Comment by zeromus** [comment]
It's not desmume's fault, it's the bluetooth controller's fault for not being a directinput device. Find better drivers or 3rd party pad-mapping programs
