### ISSUE TITLE
Control Sticks

### ISSUE THREAD

**Issue by OvOPlant** [TASEmulators/desmume#797]
I know this is the DS and they dont have control sticks, but I like using control sticks and I was wondering if there could be an option to set diagonal movement with control sticks.

**Comment by zeromus** [comment]
To move diagonally with sticks, move your stick diagonally.

**Comment by OvOPlant** [comment]
i try that but it doesnt work

**Comment by OvOPlant** [comment]
if i try to set my "up left" bind to up left with stick, it just sets it to either up or left @zeromus

**Comment by zeromus** [comment]
To move up and left diagonally with sticks, 
And you may also need to use this: ffb8666a8fd8e94a3dbe0d5248c5b758ca2dad97
(I believe I mentioned this to you on the forum)
