### ISSUE TITLE
diagonal control sticks

### ISSUE THREAD

**Issue by OvOPlant** [TASEmulators/desmume#798]
ya really just closed my issue thinking im stupid? clearly i have TRIED to set the controls by tilting the stick diagonally. but it. doesnt. work.

**Comment by zeromus** [comment]
There are no bindings for "diagonal" so I have no idea what you're doing. Do you want to bind a diagonal direction to the start button or something?

**Comment by OvOPlant** [comment]
bro. there's control binding options for "up left" "up right" ect. i want to bind them to the control stick but it doesnt work.

**Comment by zeromus** [comment]
There is no way to bind a diagonal stick to the "up left" etc., nor shall there ever be. To move up and left by using a stick, bind up to up, bind left to left, and move your stick up and left.

**Comment by OvOPlant** [comment]
why will it not be possible to bind my control stick diagonally to this
![image](https://github.com/TASEmulators/desmume/assets/149712688/58e1e599-084d-4006-befd-06a75b3f3989)

**Comment by zeromus** [comment]
It's not impossible. It's just never going to happen. Sticks are bound by cardinal directions. You want a diagonal direction. That is not done.

**Comment by OvOPlant** [comment]
well what about configuring the deadzone?

**Comment by zeromus** [comment]
You'll have to tell me why you need that first.

**Comment by OvOPlant** [comment]
"and a weird dead zone on your stick"

**Comment by zeromus** [comment]
Tell me what happens when you delete the UP LEFT etc bindings and bind the up/down/left/right normally on your stick cardinal directions

**Comment by OvOPlant** [comment]
it wont let me move diagonally. if i move it up left, it wont input both directions. it'll only input either up or left

**Comment by zeromus** [comment]
OK, it's as I suspected, we make a poor choice of 60% threshold. Or rather, SNES9x did. 50% is a more normal choice.

**Comment by OvOPlant** [comment]
so what does that mean

**Comment by zeromus** [comment]
ok as of ffb8666a8fd8e94a3dbe0d5248c5b758ca2dad97 the default should work for you, but you can change it as follows
edit ini file to add this to [Controls] section
`DigitalizationThreshold=30`
or whatever you want (default is now 50; don't decrease it too much or you won't like the results)
YES, the situation is this finnicky. It's impossible to do a good job here without a more complex digitalization model (newer emulators may be better role models by now but I haven't checked them in years)

**Comment by OvOPlant** [comment]
it says the commit failed

**Comment by zeromus** [comment]
http://desmume.org/download/

Nightly builds for the windows version can be found here: https://nightly.link/TASEmulators/desmume/workflows/build_win/master/desmume-win-x64.zip

**Comment by OvOPlant** [comment]
um whats that for

**Comment by zeromus** [comment]
What do you want it to be for?

**Comment by OvOPlant** [comment]
im so confused...
the thing you told me to add doesnt work, nothing changed

**Comment by OvOPlant** [comment]
but the commit you pushed for the change failed

**Comment by zeromus** [comment]
it failed on some useless dll build. the windows build worked

**Comment by OvOPlant** [comment]
aaa it works thank youu
