### ISSUE TITLE
Switch Controller gyro moves my mouse for some reason

### ISSUE THREAD

**Issue by 20stellaw** [TASEmulators/desmume#800]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.
I use a windows PC, 

## DesMuME version
e.g. 0.9.13 or git master
0.9.13

## Isse
type here what's bothering you, in a detailed manner.
This has never happened before, but when I try to use my switch controller with the application open, the switch gyro activates and moves my mouse with every movement, even though it's disabled in steam (connected as a non steam game).

**Comment by zeromus** [comment]
desmume can't possibly do this. turn off steam, reboot, disable your pad mapping applications and third party drivers. eventually you will find out what's causing it.
