### ISSUE TITLE
How do you make the mic work?

### ISSUE THREAD

**Issue by Err0rErr0r** [TASEmulators/desmume#802]
I'm playing Mario & Luigi Bowsers inside story, and stuck at the first giga bowser fight, at the fireball... HOW DOES THE MIC WORK... the only guide I could find is something talking about prefrences which I didn't find, I'm using an Asus...

**Comment by zeromus** [comment]
This has been answered a giga times on the web already. chatgpt probably knows

**Comment by Err0rErr0r** [comment]
All of the things on the web show prefrences... I don't see prefrences, or how to add a key for white noise, and mic?

**Comment by zeromus** [comment]
I just punched your question into chatgpt and it didn't mention "preferences"
