### ISSUE TITLE
[Request/Windows/Cocoa] Add support for zstd compressed zip

### ISSUE THREAD

**Issue by Immersion95** [TASEmulators/desmume#803]
According to the [wiki ](https://en.wikipedia.org/wiki/Zstd): 

- Zstd at its maximum compression level gives a compression ratio close to lzma, lzham, and ppmx, and performs better than lza or bzip2. Zstandard reaches the current Pareto frontier, as it decompresses faster than any other currently available algorithm with similar or better compression ratio.

This allows the fastest decompression as if .nds roms were directly loaded.

MAME recently implemented it https://github.com/mamedev/mame/pull/11827

**Comment by zeromus** [comment]
on which frontend

**Comment by Immersion95** [comment]
> on which frontend

I added both frontend on the request if possible :)
