### ISSUE TITLE
im not sure if its just my PC or not but roms wont run if theyre over 200 megabytes

### ISSUE THREAD

**Issue by SuperCoolBeans8** [TASEmulators/desmume#805]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.

**Comment by zeromus** [comment]
coincidence. you are only using hacked and broken roms over 200MB
