### ISSUE TITLE
Is it possible to add a window separation feature to the Desmume emulator?

### ISSUE THREAD

**Issue by 740801820** [TASEmulators/desmume#806]
I really like this simulator! However, I would like to play this game on dual screens, or perhaps stream the secondary screen to my mobile device. I hope that a window separation feature can be added.Just like the 3DS emulator Citra, where it has the ability to separate windows or stream the secondary screen. It would be great if Desmume could have similar capabilities.
![3ED2BF35203A39EB7CB7BAE47511E1BF](https://github.com/TASEmulators/desmume/assets/76911297/8521f873-b885-4a95-bbc5-77a022806cdc)

**Comment by zeromus** [comment]
https://github.com/TASEmulators/desmume/issues/278
