### ISSUE TITLE
having problems with DSi control buttons

### ISSUE THREAD

**Issue by petadapeta** [TASEmulators/desmume#807]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.

when i go to config to setup my controls its not working like the start button not working and the select button not working as well so yeah i kinda need help for this

**Comment by zeromus** [comment]
Desmume is not a DSi emulator.

You didn't state your operating system or desmume version.
