### ISSUE TITLE
I can't click on anything?

### ISSUE THREAD

**Issue by Asschilles** [TASEmulators/desmume#808]
## State your operating system:
Windows

## DesMuME version
9.13

## Issue
Every time I try and click something, it gives something similar to the coordinates(?) Now, I'm not into tech an all that, so I'm not entirely sure what it is. Maybe I mashed a few buttons wrong? All I remember was trying to play a Pokemon Diamond Randomizer and did something to cause that but now all games I try to load do it.

![image](https://github.com/TASEmulators/desmume/assets/175178418/89b002f1-4d7c-427c-9374-8e30f2995207)

**Comment by zeromus** [comment]
If you don't want to *view* your touch *input* in the *hud* then click *view* > *hud* > display *input*
