### ISSUE TITLE
GLES: GL_OES_surfaceless_context missing

### ISSUE THREAD

**Issue by thesourcehim** [TASEmulators/desmume#812]
## State your operating system:
Linux/gtk3

## DesMuME version
master

## Issue
I'm trying to add GLES support to gtk frontend, however GLES renderer keeps throwing error about missing extension GL_OES_surfaceless_context. This extension is really not present for both my RTX 3060 and Intel integrated graphics despite having latest drivers. I created a PR, maybe I'm simply doing something wrong.

Is this extension really required to use FBO's?

**Comment by rogerman** [comment]
Yes, GL_OES_surfaceless_context will be required at the moment, until I can prove that it isn't required. But to prove it, I'll need to fix some of the fundamental problems with the OpenGL ES renderer first.

After I'm happy about the ES renderer's compatibility, I'll look into removing the requirement for GL_OES_surfaceless_context.
