### ISSUE TITLE
이게 뭐죠?

### ISSUE THREAD

**Issue by nahwanhui** [TASEmulators/desmume#819]
## State your operating system: window
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
 0.9.13 
![캡처](https://github.com/user-attachments/assets/76dd1361-4c48-463a-acd5-f41f90e7705e)
master

## Isse 화면이 갑자기 이상해짐
type here what's bothering you, in a detailed manner.

**Comment by zeromus** [comment]
Post again in english with the name of the rom
