### ISSUE TITLE
Graphic problem with opengl

### ISSUE THREAD

**Issue by Felipefpl** [TASEmulators/desmume#820]
## State your operating system:
Windows 10

## DesMuME version
I got the latest nightly available on site.

## Isse
I cant see the graphics of the game when using opengl old or 3.2 - SoftRasterizer works fine. I have 16 GB RAm and an intel HD 4000 video card which runs games fine (It has full support for OpenGL 4.0). Here are 2 pics of what i see:

OpenGL Old
![OpenGL Old](https://github.com/user-attachments/assets/dcdb4d15-024f-40a7-b555-8feb40c54525)
OpenGL 3.2
![OpenGL 3 2](https://github.com/user-attachments/assets/6196d7be-700a-4b90-b0d9-34bd176d7523)

**Comment by rogerman** [comment]
Actually, yes you can. Go to this URL to find all our recent Win64 builds:
https://github.com/TASEmulators/desmume/actions/workflows/build_win.yml

Again, you'll need to test this, as this problem most likely has something to do with your Intel HD 4000. As of the most recent commit, it works fine for me:
![Screenshot 2024-08-04 143531](https://github.com/user-attachments/assets/2dd3d647-58bd-43d0-a3be-9e3b32ed5d6c)

**Comment by rogerman** [comment]
Well that sucks that you've had to go back that far.

But let me confirm something: Does commit d58c0e9 work for you? Or does this fail?
https://github.com/TASEmulators/desmume/actions/runs/10070604207

**Comment by rogerman** [comment]
Try this build: https://github.com/TASEmulators/desmume/actions/runs/9943499671

Just note that there's a bug in this build that will cause it to revert back to SoftRasterizer initially, so you'll have to manually change it back to OpenGL to get it to work.

**Comment by rogerman** [comment]
Okay, what about this build?
https://github.com/TASEmulators/desmume/actions/runs/9997707530

Note that this build suffers from the same 3D-renderer-resetting-at-startup bug as before.

**Comment by rogerman** [comment]
Alright, @Felipefpl, I'm gonna upload a series of custom builds in my attempt to fix your issue.

Try this build first:
https://www.dropbox.com/scl/fi/0c8n9hh6hnxoq70nxw9ex/DeSmuME-manual_read_draw_buffers.zip?rlkey=5289zxifozh34n2qojre1tehy&dl=0

**Comment by rogerman** [comment]
Okay, so what about this build:
https://www.dropbox.com/scl/fi/wbw8x8oyr39ifo6ki2pl4/DeSmuME-old_FBOs.zip?rlkey=kp1ynrwo8nr4h9ah016hpao4l&dl=0

**Comment by rogerman** [comment]
Alright @Felipefpl, try these last two builds and tell me if they work:
https://www.dropbox.com/scl/fi/v0y3bp3rqx3plkoe9fx6j/DeSmuME-new_FBO_creation_restored.zip?rlkey=uy60f00acy7csm19lt4oonb2f&dl=0

https://www.dropbox.com/scl/fi/k51gdh7ebm19czj0l2yao/DeSmuME-some_new_FBOs.zip?rlkey=8jqg21w7c6grd2gbg3llkw61x&dl=0

**Comment by rogerman** [comment]
@Felipefpl, I'm getting closer to determining the problem. I'm pretty confident that it has something to do with the FBOs. But to figure out what's really going on, I'm gonna have to ask you to do more in your testing.

To properly test the FBOs, I'll need you to test the following:
1. For 3D Rendering Engine, test both "OpenGL Old" and "OpenGL 3.2" options. (You've been doing this already.)
2. For GPU Color Depth, test the 18-bit and 24-bit options.
3. Change the Multisample Antialiasing option between Disabled and any one of the MSAA values.
4. Toggle the "Enable Depth L-Equal Polygon Facing" setting.

Also, I will need to know if you are using the latest possible drivers for your GPU.

These are the two builds that need testing:
https://www.dropbox.com/scl/fi/8zjbn6g2xetwlllrfgb6k/DeSmuME-clean_old_FBOs.zip?rlkey=ubw7ioymlnvuk5g9gpqjtklu5&dl=0

https://www.dropbox.com/scl/fi/m91tww0p00r745oj2ztnw/DeSmuME-new_FBO_output_only.zip?rlkey=ou49mjybsr11t60or0jxg8h3c&dl=0

Finally, I'm gonna have to step out at the moment. I'll be back in a few hours to continue all of this.

**Comment by rogerman** [comment]
Try the build from commit de9fc5a.

**Comment by rogerman** [comment]
Oh, I can assure you that all of those issue that you searched for are much deeper issues than they look. Each of those issues has to be specifically debugged and actively worked on. Collateral improvements won't magically fix any of them.
