### ISSUE TITLE
staying paused

### ISSUE THREAD

**Issue by lexhogenbirk** [TASEmulators/desmume#830]
## State your operating system: Windows 11
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version

## DesMuME version: 0.9.13
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.
Im playing mystery dungeon explorers of sky. It worked well but now when i leave a dungeon the game will pause. iii can only unpause when i go to my save state but when im in a finish a dungeon is paused. Hope you know a answer

**Comment by zeromus** [comment]
It pauses because it crashes. It crashes because you're cheating. Stop cheating and hacking. To reduce the likelihood of problems, Save in-game frequently, don't use savestates.
