### ISSUE TITLE
cant unpause

### ISSUE THREAD

**Issue by lexhogenbirk** [TASEmulators/desmume#831]
Im on windows 11, and DesMuME version 0.9.13. I have a problem with pokemon mystery dungeon everything was going great until my game paused. I got to the end of the dungeon and it paused. I can unpause it  when i go to a save state but now when im done with a dungeon my screen stays black. hope somebody knows what is going on.

**Comment by zeromus** [comment]
It pauses because it crashes. It crashes because you're cheating. Stop cheating and hacking. To reduce the likelihood of problems, Save in-game frequently, don't use savestates.
