### ISSUE TITLE
Graphical Problem with OpenGl 3.2/Old on Hotel Transylvania

### ISSUE THREAD

**Issue by Felipefpl** [TASEmulators/desmume#833]
## State your operating system:
Windows 10, 16 GB RAM, Intel HD 4000, No Filters/Scalings Were Used.

## DesMuME version
0.9.13

## Isse
type here what's bothering you, in a detailed manner.
The game displays messed up letters when using both OpenGLs backends:
OpenGL 3.2
![OpenGL 3 2](https://github.com/user-attachments/assets/de603016-64a5-49d8-9791-c05a2cf3112f)
OpenGL Old - The letters are better here but not as with SoftRasterizer backend:
![OpenGL Old](https://github.com/user-attachments/assets/5f09e213-aebb-4b8f-b17c-7dcb81e593a4)
SoftRasterizer - As they should be:
![SoftRasterizer](https://github.com/user-attachments/assets/11b474c9-66f2-4c7e-865c-54ac30bfe58d)

I wanna add that the graphics of the letters become messed up if you use any filters like 2xBRZ or HQ2X.

**Comment by zeromus** [comment]
1. this is why we have multiple options
1b. Enable TXT Hack
2. I doubt that. Couldnt repro any problem with those filters now, and it doesn't seem possible unless you're using a filter too large for your monitor and the screen is then scrunching back down

**Comment by zeromus** [comment]
Pics or it isn't happening
