### ISSUE TITLE
[LINUX/GTK3] Whitescreen freeze when pressing square on ds4

### ISSUE THREAD

**Issue by Connor-Kolan** [TASEmulators/desmume#834]
## State your operating system:
Linux CLI and gtk3 

## DesMuME version
0.9.13

## Issue
I play with a ds4 controller and have used steam and AntiMicroX to remap its controls to the keyboard, the bug occurs on both.
I bound the square button to the "J"-Key on my keyboard which I then bound to the "Y" Key in desmume.
After loading a rom and pressing the square button, desmume seems to pause/freeze by switching to a white screeen and playing the same audio frame all the time. I can then press the square button again and it returns to normal. This only happens when I press press square on the controller. If I press the "J"-Key it works just fine.

**Comment by thesourcehim** [comment]
Check if square button is bound to anything in the emulator settings, maybe something else triggers beside Y. Also please attach here your AntiMicroX configuration (amgp file).

**Comment by Connor-Kolan** [comment]
The button is not bound to anything else. What I have noticed is, that the error seems to only occur when using the controller in wired mode, when using bluetooth the bug does not occur. 
I wont let me upload the file with the original file ending so I renamed it to txt but this is the AntiMicroX config
[t.gamecontroller.txt](https://github.com/user-attachments/files/17134684/t.gamecontroller.txt)

**Comment by Connor-Kolan** [comment]
I've tried it again and it seems to only happen when I start desmume for the second time after connecting my controller. If I reconnect my controller it works again.

**Comment by thesourcehim** [comment]
@Connor-Kolan I just came back from a buisness trip, I'll test with DualSense (I don't have DS4) as soon as I can.

**Comment by Connor-Kolan** [comment]
Steps to recreate: 

1. Connect controller
2. start desmume
3. boot rom
4. press square 
5. white screen

Steps to fix:

1. disconnect controller while desmume is running
2. reconnect controller 

My config file: (again it wont let me upload it without renaming it to txt)
[config.txt](https://github.com/user-attachments/files/17292797/config.txt)

**Comment by thesourcehim** [comment]
I'll test tomorrow but I can say that reconnecting controller while desmume is running changes things because gtk frontend does not support gamepad hotplugging. So after you reconnect controller desmume only gets keyboard input from antimicrox, before reconnecting it gets both J and square

**Comment by thesourcehim** [comment]
Got it. In my case it's triangle but all the same. Reason: your config does not contain any bindings for gamepad so desmume uses some default bindings and it happens to be that square is bound to Lid close thus the white screen. Workaround for now is to bind gamepad buttons properly (Edit joystick controls in the main menu), I think I'll change default bindings to unbound for every button that is not in config file.

**Comment by thesourcehim** [comment]
@Connor-Kolan please test PR #845
