### ISSUE TITLE
Desmume Nukes the Audio Quality Of Everything On My Computer When It Is Open

### ISSUE THREAD

**Issue by marebearexe** [TASEmulators/desmume#842]
## State your operating system:
Windows

## DesMuME version
0.9.13 x64

## Issue
This isn't an issue I have with any other emulators (mgba, citra, etc.) I also didn't have this issue prior to today. Whenever I open Desmume, the sound coming from it is very low quality. It isn't crackly or staticy, just low quality. In addition, anything else that plays audio on my computer, so long as Desmume is active, also produces very low quality audio. When I close Desmume, the issue stops. This does not occur additionally for any other games. Just Desmume. 

I was able to fix it temporarily by switching my sound core from Direct Sound Interface to Xaudio2 Interface. But when I closed and reopened the ROM (not the emulator, I believe, but it could have been the emulator as well,) the issue resumed and could no longer be fixed by switching sound cores. It's driving me insane. It's like the audio goes from that of a 720p video down to a 144p. It sounds awful. Please help!!!

**Comment by zeromus** [comment]
reboot your computer or something. problems that never happened before will probably never happen again

**Comment by marebearexe** [comment]
Well, it's still happening. I don't know what to tell you.

**Comment by zeromus** [comment]
use system restore or whatever to rollback to the system state before windows (or you) updated something which broke it. It's not likely that reloading the rom changed anything, but restarting the emulator may have reverted the audio output to directsound in case your system is suffering from very dire problems. Directsound has the potential to cause buggy audio drivers (and ALL audio drivers are buggy) to glitch other apps. Although at this point it's just as likely microsoft broke their audio stack. They're doing that all the time.

**Comment by Jules-A** [comment]
You can try updating audio drivers but honestly you should really avoid Direct Sound, it's old and abandoned (well so is XAudio but it's at least newer), only really meant for XP or older systems and really shouldn't be the default on new OS's.

Are you saying that Desmume is reverting XAudio2 to Direct Sound or are you manually reverting back to Direct Sound?

**Comment by zeromus** [comment]
It's only my guess that it may be reverting to directsound after choosing xaudio. Desmume does default to directsound (probably not a wise choice)
