### ISSUE TITLE
[linux] editing controlls sometimes (often) freezes the emulator

### ISSUE THREAD

**Issue by intra0** [TASEmulators/desmume#843]
Tested using the newest commit as of october 2024, built using gtk3
![Screenshot from 2024-10-05 19-34-37](https://github.com/user-attachments/assets/e18efa76-85e2-4b7d-a0ed-fea0bc645684)
when editing controlls, if you are not quick enough (and 60% of the time even if you are) the emulator will hard freeze.
music will still play, and the game will run, and if you already have some controls set up by the time it freezes, you can use those buttons.
but when I say it hard freezes, I mean it becomes impossible to quit the program. none of the UI is interactable, and alt+f4 does nothing. only thing that works is opening up the task manager and killing the process.

**Comment by intra0** [comment]
This issue was reported for the flatpak version in #731 but it happens on *all* linux versions of desmume

**Comment by thesourcehim** [comment]
I tried to reproduce using my local build, but no luck so far. Is it exclusive to flatpack version?

**Comment by intra0** [comment]
No I compiled the latest commit from source and reproduced the issue
also happens in the fedora rpm fusion version

try opening the change A button and leaving it for like 30 seconds to a minute

**Comment by thesourcehim** [comment]
I started a game, then opened 'Configure joystick controls' window, pressed a button at the top (configure A), the emulation paused, which is expected: the dialog appears waiting for the input in a loop in the main thread. I waited for a minute then pressed a button on my gamepad, input was accepted and emulation continued.

**Comment by rofl0r** [comment]
wayland vs X11 issue maybe ?

**Comment by intra0** [comment]
I am using wayland. what distro are you using @thesourcehim ?

**Comment by intra0** [comment]
and it only happens for joystick controlls, does not happen for keyboard controlls, are you using keyboard @thesourcehim ?

changing the focused window while this is up can also cause the freeze
![image](https://github.com/user-attachments/assets/a63a5956-9835-4bb0-8da0-4ac817af5256)

**Comment by thesourcehim** [comment]
Yes, I'm using gamepad. My system is Fedora 40, Plasma 6 wayland.
You can not press Ok or Cancel until you give some input from your gamepad because as I explained earlier application enters a loop waiting for input. This can lead to a deadlock if for example gamepad gets disconnected while app is in the loop (hotplugging is not supported). I agree this is not the best way to configure controls, I'll rework that dialog to get input asynchronously. For now you have press something on a gamepad to exit the loop.

**Comment by thesourcehim** [comment]
@intra0, please test PR #845

**Comment by intra0** [comment]
>  I explained earlier application enters a loop waiting for input
sorry I read it but didn't fully process it at the time.

Tested PR #845 and it totally and completely fixed this issue. it no longer dead loops when I press edit controlls, and the cancel button now works.
