### ISSUE TITLE
DeSmuMe can't load from /dev/cdrom

### ISSUE THREAD

**Issue by s0urce-c0de** [TASEmulators/desmume#849]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.
![image](https://github.com/user-attachments/assets/d75fb976-4af9-4595-8b62-f9dd96c09d21)
## DesMuME version
e.g. 0.9.13 or git master
v0.9.13
## Issue
I have some of my nds games flashed on CDs (`wodim dev=/dev/cdrom POKEMON_B2_IREO01_00.nds`) and I can't load these into desmume, it doesn't get the CD started on reading, and if i dump the cd's contents to a file (`dd if=/dev/cdrom of=pokemonblack2.nds status=progress`), and I load that, it works fine. I was hoping this could be fixed so I just have to load my CDs, not store all my game files on my Computer.

**Comment by zeromus** [comment]
Desmume is never going to open a raw cd rom image which you have for some unfathomable burnt on it instead of a filesystem

**Comment by s0urce-c0de** [comment]
> @s0urce-c0de I am curious, why do you burn a 256MB NDS games onto a 700MB CD, and more specifically, why not just as a file so you could fit both Pokemon Black and White on the CD, but you write it as the actual raw data. Would actually be kinda neat if the emulator would then write the save onto the CD-RW aswell lol just like on a real cartridge.

I have big games like 680MB stripped

**Comment by zeromus** [comment]
NDS games read randomly and expect it to happen fast. Reading randomly from a CD will render the game unplayable. You would have to use the desmume option to read entirely to memory and then wait for it to read the whole CD every time you load a ROM.

Since you're on linux, make a tiny fuse script to mount the contents of the disk as a single file named poopfart.nds

**Comment by zeromus** [comment]
ask chatgpt for help. I may as well give you the prompt I just used

> write a fuse script that exposes a cdrom's raw (2048 byte sector) contents as a single file called poopfart.nds

**Comment by s0urce-c0de** [comment]
This content may violate our [usage policies](https://openai.com/policies/usage-policies).

**Comment by s0urce-c0de** [comment]
[Screen recording 2024-11-14 21.28.37.webm](https://github.com/user-attachments/assets/7ffc5b9e-afa0-4075-9b38-6e38c2e321da)

**Comment by zeromus** [comment]
That was a video of you NOT trying to fix it

**Comment by s0urce-c0de** [comment]
I have no idea how to fix it. I don't use AI very often.

**Comment by zeromus** [comment]
Identify something objectionable in the prompt and change it so it's not objectionable

**Comment by s0urce-c0de** [comment]
hmm lemme see
