### ISSUE TITLE
No Audio when Ensata Emulation Enabled

### ISSUE THREAD

**Issue by dlbuhtig4096** [TASEmulators/desmume#850]
## State your operating system:
Windows11

## DesMuME version
nightly

## Issue
Games output no audio when ensata emulation is enabled.
Once ensata is disabled, audio works again.

I am not sure if links are allowed here, as they are related to the Nintendo leak occurred in 2020 and GameFreak leak happening recently.

**Comment by zeromus** [comment]
don't hold your breath for this to get fixed. The ensata protocol could be doing a million things. You guys with whatever test case you have need to go figure that stuff out on your own.

**Comment by dlbuhtig4096** [comment]
I was just reporting it first.

Ensata has a debug register 0x04fff200 that is not emulated by DeSmuMe currently, which seems to be the option to enable / disabled sound.
When Ensata emulation is enabled, the game writes 0x10 to 0x04fff200 and get 32 bits response from it. If it returns zero, then all sound would be disabled.

So here's the quick fix to this:
- At [MMU.cpp line 2473](https://github.com/TASEmulators/desmume/blob/2bc5b0d86b56a6e163d048b5be52e5cfc74043e6/desmume/src/MMU.cpp#L2473-L2478):
```		if(nds.ensataEmulation)
		{
			if(addrMasked == eng_3D_CLIPMTX_RESULT) return true;
			if(addrMasked == 0x04FFF000) return true;
			if(addrMasked == 0x04FFF010) return true;
			if(addrMasked == 0x04FFF200) return true;
		}
```
- At [MMU.cpp line 3836](https://github.com/TASEmulators/desmume/blob/2bc5b0d86b56a6e163d048b5be52e5cfc74043e6/desmume/src/MMU.cpp#L3836):
```
				case 0x04FFF200:
					return;
```
- At [MMU.cpp line 5485](https://github.com/TASEmulators/desmume/blob/2bc5b0d86b56a6e163d048b5be52e5cfc74043e6/desmume/src/MMU.cpp#L5485):
```
				case 0x04FFF200:
					return 1; // Or perhaps some ui option flag
```

**Comment by zeromus** [comment]
great work. you're on track. do it on a fork and test it and send a PR

**Comment by dlbuhtig4096** [comment]
Just tested and it should works. Please check #851.
