### ISSUE TITLE
was playing kirby super star and i click something else and the screen porpotion went weird

### ISSUE THREAD

**Issue by justbequickimjusttryingtomakeaccount** [TASEmulators/desmume#858]
im using windowns
## DesMuME version
e0.9.13

## Isse
was playing kirby super star and i click something else and the screen porpotion went weird
![Screenshot 2024-11-01 001345](https://github.com/user-attachments/assets/b8984fd8-6040-41b7-b6bd-bb23858bf914)

**Comment by zeromus** [comment]
view > pad to integer. If that doesn't work, delete desmume.ini and pay more attention next time.
