### ISSUE TITLE
Lua scripting causes fast forward (speed up) to lag extremly

### ISSUE THREAD

**Issue by vQuentiX** [TASEmulators/desmume#861]
## State your operating system:
Windows

## DesMuME version
e.g. 0.9.13 or git master

## Isse
I want to play pokemon sacred gold on desmume and use pokelink with lua script and if i want to use the speed up, it causes extrem lags. im not very good in programmer stuff or anything so i dont know how to solve such a problem, maybe you can help me with it :)

**Comment by zeromus** [comment]
lua script slows down emulation. accept the consequence.
