### ISSUE TITLE
One of the best DS emulators I could only find and it lacks tools to rip sprites from!

### ISSUE THREAD

**Issue by Philgamerk98** [TASEmulators/desmume#862]
Hi. I just started using this thing the other month ago and I did not noticed right away until the moment when I found something I wanted to rip from with a DS game and to my shock unlike some Super Nes, Nes, Genesis, and Game Boy emulators out there, this one doesn't have anything to rip whole sprites or backgrounds besides taking screenshots that doesn't rip the whole graphic in the game! :( 

I would be very happy if you guys reconsider taking requests even if you are no longer updating this shamefully dead emulator that should deserve more better love and care with it and not just get mistreated with very few features when this emulator could been useful for not just DS gamers but also people who like to rip graphics from DS games! 

Please think about improving this emulator again and add those features for ripping the sprites! There should be at least a button to simply dump the graphics from the map viewer and tile viewer. I also wish for you guys to add a button to save palettes from DS games.

**Comment by zeromus** [comment]
I just grabbed this from super princess peach using tools > view maps

![image](https://github.com/user-attachments/assets/1cc9f605-7963-4b23-a6fb-cc67be854a6c)

**Comment by Philgamerk98** [comment]
> I just grabbed this from super princess peach using tools > view maps
> 
> ![image](https://private-user-images.githubusercontent.com/102701/383031787-1cc9f605-7963-4b23-a6fb-cc67be854a6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzM2MTIsIm5iZiI6MTczMTMzMzMxMiwicGF0aCI6Ii8xMDI3MDEvMzgzMDMxNzg3LTFjYzlmNjA1LTc5NjMtNGIyMy1hNmZiLWNjNjdiZTg1NGE2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMzU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mzk4ZjBjZmQ2M2ZmNWY0YjI0NjI1ZGRiOWM0NmNiY2RjNmJkZDFiZWU3YTg0MmI5N2JiZjgwMGE0NGYxZTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kxqsvRe6Dz0JXRkPZSgXZcDNhOHc33O1XBMPJbQwDnc)

but that still don't work because in my case if you screenshot from the debug viewer for the sprites and backgrounds since there is no "dump" or "export" button you get slightly blurry and shrinked sprites because the program wasn't designed that way for ripping and was only put there for just show and tell without making any use for actual best quality ripping. The program is just useless for capturing sprites from games and doesn't even provide support for extracting 3d models from certain ds games that have 3d models. :( 

this emulator should only be considered good for just playing games but I can't recommend it for ripping sprites and models sadly enough. So its probably best to look for better alternatives for that reason unless preservation with archiving art of our childhoods is not your concern lmao.
