### ISSUE TITLE
Linux Enable Screen size ratio

### ISSUE THREAD

**Issue by wingedonezero** [TASEmulators/desmume#866]
I noticed on the windows build you can do the different ratios. That is something your not able to do on the linux build. Any chance of adding that? It be nice to have the bottom screen be smaller in fullscreen. Windows version doesn't work well with wine. But that feature would be nice to have available as having both the same size in fullscreen isn't as enjoyable.

**Comment by zeromus** [comment]
[ Linux Enable Screen size ratio #866 ](https://github.com/TASEmulators/desmume/issues/209)
