### ISSUE TITLE
pokemon heartgold the skiils of pokemon dont show and the screen blacked out after the battle

### ISSUE THREAD

**Issue by Vanlalhlim** [TASEmulators/desmume#870]
## State your operating system:
Windows/Mac/Linux. in case of linux, whether you use CLI, gtk2, or gtk3 version.

## DesMuME version
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.

**Comment by zeromus** [comment]
stop using ancient versions of the emulator. stop using savestates. save in-game frequently, close the emulator, open it again, and load your saved file from the in-game menu,
