### ISSUE TITLE
please add switch 

### ISSUE THREAD

**Issue by user18081972** [TASEmulators/desmume#871]
hello mister zeromius 
please add support for the popular Nintendo Switch system to this Desmume simulator program, so we can play pokemon scarlet on it. Much thanks
ps: my aunt have birthday 🥳

## State your operating system:
Samsung

## DesMuME version
e.g. 0.9.13 or git master

## Isse
type here what's bothering you, in a detailed manner.
No switch :(

**Comment by zeromus** [comment]
https://www.google.com/search?q=nintendo+ds+emulator+on+switch

**Comment by zeromus** [comment]
desmume is not and never will be a switch emulator.
