### ISSUE TITLE
Black Screen on Pokemon Soul Silver (Storm Silver ROM Hack)

### ISSUE THREAD

**Issue by Xenon0138** [TASEmulators/desmume#875]
* Windows 11 DeSmuME version 0.9.13
Everytime I load my save state the top screen is stuck with a black screen while the bottom screen works perfectly fine. I've reset the save state, the ROM, DeSmuME, my computer; nothing has fixed the problem.

**Comment by zeromus** [comment]
Stop using savestates. change the 3d renderer to softrasterizer. Stop using HACKED ROMS WITH BUGS.
