### ISSUE TITLE
Request: Backup battery save when loading savestate

### ISSUE THREAD

**Issue by Shananiganeer** [TASEmulators/desmume#877]
## State your operating system:
Windows

## DesMuME version
0.9.13

## Issue
Please add a config option to backup existing battery saves when loading a savestate, and make that the default behavior.

Something as simple as copying the existing battery save to \<ROM name\>-backup.dsv when overwriting would be sufficient to give a disaster recovery option for an unintentional keypress. This could be extended to be more robust by storing the last X number of backups and/or appending to the name the last modified timestamp prior to the overwrite.

**Comment by zeromus** [comment]
nope, discussed on #876
