### ISSUE TITLE
DeSmuME snap app cannot be run on ubuntu

### ISSUE THREAD

**Issue by binocry** [TASEmulators/desmume#878]
## State your operating system:
Ubuntu 24.04.1 LTS

## DesMuME version
0.9.13

## Issue
snap from DesMuME refuses to open, this is a report from the terminal with the command "snap run desmume-emulator"

snap run desmume-emulator
ALSA lib conf.c:4553:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
Failed to open device: No such file or directory
Microphone init failed.
DeSmuME 0.9.13 git#0 x64-JIT SSE2
CPU mode: Interpreter
Gtk-Message: 09:44:05.803: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.153" is not allowed to own the service "org.desmume.DeSmuME" due to AppArmor policy

(desmume:6258): GLib-CRITICAL **: 09:44:06.020: g_key_file_free: assertion 'key_file != NULL' failed

**Comment by rofl0r** [comment]
we don't support snap build, what you're using is made by a 3rd party. you should file an issue there.
