### ISSUE TITLE
very slow loading

### ISSUE THREAD

**Issue by confusedman163** [TASEmulators/desmume#879]
Windows 11
DesMuME version 0.9.13 

Upon loading the save file the screen stays black for a very very long time

**Comment by zeromus** [comment]
stop loading files off a very slow external USB stick, I guess.

**Comment by confusedman163** [comment]
Hello you stupid fuck, I’m loading off my hard drive. I guess my hard drive
really is a “slow external USB stick”. Also sorry that your mom hates you
so much that you ended up a snob like this. Fucking idiot.

**Comment by zeromus** [comment]
Could also be a sleeped hard disk spinning up. With no efforts at providing useful information (which game, what you've done to hack it), these are the only guesses we can make.
